apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:jtATVtxWp2ErCMRE/gDHquBk3QQyVGeqI1xV9+IveMwGCZf7Rh3+Zf85VbFBU6ozv+mU0A3qGxxDC+z4zP00yOi3LWl3HW53L6RrSf6JM+ER3nz5oU+5o3scxRXo785l7t2qvdU5b6khABaqP8i3YuV+ndIzssUjXaKFoAvz57hCs6ZgiKIzs2wyXZmGH5vXyuC6EqTJRKkO+cxtgqgu4lfW8KoJcs3l31t1YYp0tSx21fZWcB94fx0ax5h05LR9PhuDQbWkkUnBeKxVGA1fND2VYuJjwxmugR0qz+mF+ZpbnncR+aQnCyrjj9c=,iv:Ed1HCxvy9SgjR8EjI8HC6ylxII8oM4SyDWMrq9LzIdk=,tag:2yOJNbmXUB7R6u48OMNpqw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSDZ1ZTM3enBZeFdZaklp
            dENFaUZOeFd4TnE4N1NCOHpRRkIvUnJ4ZVdZClZNazZFWW10aEwzZjdYeVdEc2pS
            RXM4ZG1yTjJGMkhKQnRlUm1SR0Z1alUKLS0tIEpOMTlUZnI5a0FhMnpGVTV1MDM4
            cUFPcVZPejFCSG5KUjdGcjdsNWFkWWsKWwR22GtogeehRgR6TnBEwSt2lQXalCa6
            qbqk/tYoMWf3IxK39rI24LK/D8zi7Q0WwfpBmhRtUICQDrdN7RyWdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T22:20:29Z"
    mac: ENC[AES256_GCM,data:fNtfb2jEghkPQGheLDeefa/a9775OHeHj0oj419E7fd8tBgl+q5DObPaNYlpPHtk5rkaD0hUkKy/gZo61Yu0OwBr84qR99HuRlGgOmoX2htr4Bdjc2GjSaasmtXf9/ItQCsVvGbHjd0uvGgQKeoTyLk5rDkeStcUXLeehnh8f5g=,iv:dgxAQ3t2wyM6EAus2ki1isniOiZqSq4PEwUMmrU+As8=,tag:mRgVtKBpS+tAUi3/S0cogQ==,type:str]
    version: 3.13.1
