apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:owQfliXIJPYp+eCVjQjfe18SepFBmQ5wH43uhy2cH0EtjvIucRtIc0C6xkzxcaMUnmQw8nyG5ZlhIYefUYPxh6mo6DGgp1tukByml/KB4vVeQOE77mYCew1rlLeBXtI46vckMAglLsbpcbOLF5BcQddpXxAolLVb8srlz6IODnL+HiCgjsDENOQThwGLmy3zl0cHcnVu44Yv4gFPL7P1Yz99XuedYp9SbK0PQ13tkAHFXCmKQX92EaXyWjbhIENMF+pMoeEPlWhUDpPBTJ2Ypl3l0SwIxDafF9GMAn6R56Z/I+2ivuWocjMxW+g=,iv:cgn/jmFYRXWhIQ5CIqW/dEhdCUGPiMaJ9DY2p8Jo6ZY=,tag:Nw6dVprZ89fEmcFdB9Ix8Q==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: media
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRFozQXVPRTErUHFNYnRM
            YkZyVlc0aURNVWVnSEl3L2JnbkRzaGRQS2hzCndpckg4WjFjQ3AvM05QdFcwenIx
            aDU3YnR1NnpmL1JzNFJzOWczZDUxR0EKLS0tIEg3R0doZWdSOFZ1a004Q1N2akRy
            SGZvSFNkdFJEOGVlcytnejRaYk1veTAKdDfQqVTYypKTF83Q0txtmIcCfazE4AB/
            YyaoUES8oLlO66Zm4NOlr9zLvMcFl62WKxolo9v+duWsg1zVtuIEUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T22:38:31Z"
    mac: ENC[AES256_GCM,data:bzNE7Ks+P1D310TB44mVpKWTrDE/k/PVAJYD91DGL9PwGzSRl//Y3Ai7QxZbvM7sx/xT5hSme4ixveXb+MwyCQ3C6KUx77mszFSz1qgNQMdxdKHi94QtIaWplGaVAzvjdofwYihLBO2W6OEpvef2Z8JRtoZvlL7cbK59qtzp4go=,iv:/EEmQtp99GXVvOs7Q2Znil0IOJHPqO+oNzRXO+aEHvs=,tag:8KB2mU2ERvj2phPitxPALQ==,type:str]
    version: 3.13.1
