apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:IiVpKYoAP1vbBlLvrOnggaD8lP+bD9cOjuXq0ejr1SR0CnuBXOx+8f1FbrHO0wLWiO2x/MP2z8aZGsmy3vijC6f5cXGjUL3z8jPTa+P8UWTOXMGLmK4UnHzYBSXJ7VbCaYhTas9muhEGQncX5u3WvlL56EPe1zTyVQsWihS6ewMruWE5ACLhPS47TL4PzOHtrD6HWFU3E09ME2BPWkqFeKn3wtLQaOkqOGmAyUf9aSxFN6NTmVmEepaOGWFfgdgnKA8Ns33uujQd7TgdTOOpwiCXZAS4HqnLO+YGvbDvjUUKnZ5dYMdPdJ6Bl6w=,iv:2uHe++Fk+ISOHaoBr/PfIqVfZonLv5kJzGvBREHH5Ek=,tag:RFu8sCFkKFxr88FnwRS7EA==,type:str]
kind: Secret
metadata:
    name: homarr-tunnel-credentials
    namespace: media
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bU0xMUlMc3JOOEllM0ZY
            Qkp6bTBVSTFOQi85UXd1QlJ6ZWNnc01RbFJJCnFrYlEwQlIvaThLbXZvRDQ0eDlL
            bE8wdzJFaU9GOFVCaEJwK0tWMUJIdGMKLS0tIHgva0ZKdXlWR0NNY3p1WGZ2T0JU
            SzVIR3pFc0NFL2lqZm9WUW0xYXdPTjAKquNIliTzhS2f5NoPXwNd7LrQXQ8sNi2a
            drDmURwRcL8z8kDlA3d+DXgGO7Y4IUB2fQbOk7dWj4wSHIC+61aObw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T22:44:40Z"
    mac: ENC[AES256_GCM,data:G8sRJFpb8MYXcTzPmyLiy2a/lGlFJ+FRchh3np3VOAO99r4pPTlGSP7HmrkLIGPrr+/XX6eMdZ5C0P6ne9p7uCagSjr5lYXWSVh7Drnq74X3kMnC/Q2ezvt9vrDW6mobr8OgtZugZaUrChBpOUUS154qWNMvDTLebXgzapktvWI=,iv:RqMoyV4No/InHf0DR6kWvhX15Xn/orrCYhoGmVNUFOc=,tag:c3KFxjpdDWUcqne3jQXfLQ==,type:str]
    version: 3.13.1
