apiVersion: v1
kind: Secret
metadata:
    name: homarr-secret
    namespace: media
stringData:
    AUTH_SECRET: ENC[AES256_GCM,data:QcQHEsxkcKaHWAY7knIOHneASFuDTgYP/BVWjRIv8bqkcvWHoRhjxh4Cmf0=,iv:jtPzUmp0mR+nwLTXowE01XHblzQyceq63nd9klKetsA=,tag:/arDewBNywzId5+qRVWyZw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUR0swYURpOWpSRllnSjJy
            NFFseG9tN0U0OThPVGNXenBoYW1MN2Z2OFZNCjlLQnpVN0JBcGtPOVFDSkV1SUs0
            SVA0UUo1djNNLyt4cmIxWkxldHZXSDgKLS0tIFNJb1drVzV2TWplREhmanVESUp5
            V1gvcGFZdVh4cWVsajdNRXFod2YxWlUKZppbT8NFbNbqYISJtS7xN3xP1zXO5miH
            y4CwHVKALzMiG+7KUbh8+kewboisNE+zSfJYJ5q8qo4bluc94/qRFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T22:16:41Z"
    mac: ENC[AES256_GCM,data:4E49hgTvp8i+TGpY/weTTjLmfqREh8zMwnpxv2h6nRyU8jAw1izjcX/MeqC8BJoPB9gSNzHBi4Oj2WIVv92a2oO84Eogct72APErnylzkl/xydBsf0xq6IqJcNx9l0vVlv90Gui/7NgSPqaqp24lJ+PJD6OeIpjnWWRdcM1n4LI=,iv:r5clTAyprw2hQmPYXTBIwdb8/cKCgv5RPEbdlF7egBU=,tag:Rid+EXtd9RaN4Bv4LMUwHA==,type:str]
    version: 3.13.1
