apiVersion: v1
kind: Secret
metadata:
    name: homarr-secret
    namespace: media
stringData:
    SECRET_ENCRYPTION_KEY: ENC[AES256_GCM,data:8edyVint7CCZv3ZeWLQ7C9Hw8dsmCdX72fJOl21EYxNBDx+sK7AdpCI4uUUBrtfBhAEReeqHjWdzq2sSfh3Jxw==,iv:Tp9YVIONtOsjoz3HaDYc/ftLsj+W7rYC4tzPibM0b2o=,tag:F8NcZtZBUKny8IF1Oab28w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRGExbVF4WnFqTytHZld0
            WFNLb1FWbEtxQmNJaWJSaEFaMFlrZi92cEZNCnVsTmwrN2o4dkk4NG1Zd1hDVEZw
            L3dTRmxuenJ4NFFKMHNjZDBPTFBmc0UKLS0tIDRtV3pGRHhYWUQzNkFCMXY4K25P
            dDdzZDdKNTBDWHZuaVhNRmowQUIzVTQKHDL0pvblxx7Ul5dMcBhcqeTWBnRGF1E2
            o1nVxbPc4InBLP9qyRmmqX+TZ7/JT+ArNdLHtHvOLmhZ/jit6z4U0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T23:02:19Z"
    mac: ENC[AES256_GCM,data:OJFIhUZxtqGKkfubFb26q2Co5HWvtDMpSVmkDJKst3WQSl+XM9VaR7WJmKMPY8XYFK3+IEV8fN7vHCboJ+DOOuHU5J78F+eG99e5ya9KGNekwKzBZhFpLGCWuX7iKzYtb8x+Gc2LhBGRLKcoRzq1BfFDgReC/TftIeZLo1KQY+U=,iv:sgtGKVI0oe4W+sWzNBO52WzWNNbwknwhWtDfd385vH4=,tag:2LiMoPP0J00aPkpl3/gSKg==,type:str]
    version: 3.13.1
