apiVersion: v1
kind: Secret
metadata:
    name: vikunja-credentials
    namespace: hermes
stringData:
    VIKUNJA_PASSWORD: ENC[AES256_GCM,data:j/ojuMII2KGNM6pK,iv:23hsdFXr8UqobKTbTVl6/Ymlypok2Vv/7FsMXC/IDL4=,tag:JuBZUwOp28m+z2fEFuX08g==,type:str]
    VIKUNJA_USERNAME: ENC[AES256_GCM,data:Il2THg==,iv:gFtlMDga7EK5uhCHvmuteQQYD/1dXTz0vDuJjqpx+4Q=,tag:+wxaAYNyZlFKNKGT5DqiJA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMmhMNXduQm1ldzBEck1Q
            YlRTZ3JETEU3M3ZGTXEzL3BtcFcrTXViVjBzCkRaRHJOQUFQZTIrSE9NZjB4NjdT
            OVloMWQvcTdXcVQxMkV5MFYwN21HbGMKLS0tIFNLUFNlT1ZrN3VwNmNNTEtlcnU5
            WWNsSE50cTh1VVJDNFllUGJ4c0FPZzAKX8qmWuoi7oQMaorY/NPz0l0WSRXsEAh5
            88axTFMVa+Q8DyaCe1SfEiK8xHs4tT8YOiPZ9qrJB5MESN7YRA4ZWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T14:53:35Z"
    mac: ENC[AES256_GCM,data:zH9k+/zsaD9WsIldtoTLb6Sd8MvPK5xEfmj8Dt5y3WdjDnGfDO7TFxfjLw9UgdsDdr54m3U5qJtMj79Hba6f/Lg6ZREOkxuB06Cr91Ed+7hzvoghHiRAjgl+rSsYe8QQD4+FaByLvUG0oUotVtOCYR22yTBIExzi+cJnxcPL7WA=,iv:nzIiIPsvxVzMINjMH/4WMAlcJWDJYVzU2F657ehJkSs=,tag:R8WIXQUQf6k5xUAIMewxQg==,type:str]
    version: 3.13.1
