apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      securityContext:
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
      containers:
        - name: wordpress
          image: wordpress:7.0.0-php8.4-apache
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: wordpress-db
          env:
            - name: WORDPRESS_CONFIG_EXTRA
              value: "define('FS_METHOD', 'direct'); define('WP_DEBUG', true); define('WP_DEBUG_LOG', true); define('WP_DEBUG_DISPLAY', false);"
          resources:
            requests:
              memory: "512Mi"              
            limits:
              memory: "2Gi"             
          volumeMounts:
            - name: wp-content
              mountPath: /var/www/html/wp-content
      volumes:
        - name: wp-content
          persistentVolumeClaim:
            claimName: wordpress-content
