apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:0Ei9ylB3TidP4b8O3bpVO7EyY+t+bd3Bp4IB0qldHkuhArqR/wjgeDC6tRaFdbELl2TC9ypQBb8fx1sUxqMpPTFkmfva3hFmdmTQdoONsVk8uQ2xIcA6Z7XBLW3A0iRU2wyDq4xpxyfJC6rB1/K4oPTN81F/5pww6Dc3j6y/1EgvR/M5ccO60AMFKsAHzdynOdMB/S/Ez5A20IWzKYI5EYAkuQrNNObIlCgqasPdfss/Xn0NSsy9smjFZHRYNigWjEFDbybD0uZMgYfNSAwKw8n1ooaQTX4Xksf8sYqv4x8whVo1PMI5DWUWQwU=,iv:YFqeGt7sCMrXNAEnqgYd3UfXd6E8rgol/s+gaQUqpaw=,tag:DGkVvtfkoOp4E/AlbjdMrg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NWVzYlBnaHlXNDVGN3g1
            aGNkL0NSVmlTOG9ydExYS2tiR1I4UUxkZURFCmVYcHlXaHhVcmNnVkhGYlE0eU9Q
            cjZmRE9NNHFreDRuVTU5ZjUrWHAxT0UKLS0tIHozaGIrRFh0UDBBK28zRHVxZnZi
            dnFYcFFaK2RsMDBqdVZwVHhxY25rS0EKYuRaa05O5wHgo6MOSYX/Bu8ldwNlO+tF
            MlQEf6BKG9LhYc4s6ZUai6r38NQESV4uLOf/azwQLudURCz3LhGqRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T23:31:29Z"
    mac: ENC[AES256_GCM,data:i2vnVfXH+Fq1oKRcGS/pbk7ggQaIyBcQulCbDtkrXxNQpMJdi9Yey2VytwhtJ8hqq7iK9Dp4WuCa51dpVnXGPkgr7V2O+BH8GZ6G0AuQd2UuKniXVzNTlF8ouiop7ILvsOIEW2TUpFyvZoGjD+n2aYIzLm9z09H99/Faizu8DzM=,iv:p3oIBagto10t/t31WPBaPnfXanu/FR3IKiItTanTrMA=,tag:CK36vJgEPduuqHaizGB8nQ==,type:str]
    version: 3.13.1
