apiVersion: v1
data:
    WORDPRESS_DB_HOST: ENC[AES256_GCM,data:L/yUZRRJi6z4H5jh2kzQn2N0wIeTJq12iXVYhP78uQjYUyH3T3Tsfb6sCjk=,iv:Lezi3L4IhUXWakmdPgAPVZ4b5eVG+kYm7rEpMZ6T6eI=,tag:B8kj58xMumwBDNXQ5HJPxw==,type:str]
    WORDPRESS_DB_NAME: ENC[AES256_GCM,data:LW47xlX1DyWiNB40,iv:5ay2uLosS+wrOin7xy7wdRPNMjJXiPsgAUC/3+UkjvU=,tag:53gRH7t2ohRtG2o/7kUjpw==,type:str]
    WORDPRESS_DB_PASSWORD: ENC[AES256_GCM,data:epSRME6NnJ3Uky9sGFgEaQ==,iv:AN73aUBtY8pziUFL5Y0dK+ICDpg8fbY/zazAuSWMYd4=,tag:ZmeWXbxJKUnwCzByHyxzzQ==,type:str]
    WORDPRESS_DB_USER: ENC[AES256_GCM,data:Syi6+ivQQyrBj4ZWTQv/aQ==,iv:QMPddKgh+4zKMrIArjxkYQCgfrrflUs8UNH2XgV3X18=,tag:LiH2fHboAN+Ck3608TCfvA==,type:str]
kind: Secret
metadata:
    name: wordpress-db
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbXNER3ZEZ21JZTA3b3Fo
            b21yVm9MenlReGF5R2FGRWZqMW8vc1RzV1RBCjU0ZHR1Vk1HbnlFWVpPSHhObFMz
            ZzBOM0hUWld0QWgya3lPM2ZTZFU2b0EKLS0tIG9IU05FYVFKSE1ManAwUGZJTU9F
            RjBPM0tuMnVWY0JpWmFqL0xML2RWQmcKlptraUM7xDcHSqe2pvlvg5I5f+I3fJJr
            ijDEpb4jtTmMz69s0EMrCjiyATkSJj8ueOX1cwshTOFDHsmlnQNx2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T23:44:43Z"
    mac: ENC[AES256_GCM,data:Eygg1pj9THZ9+l3D22i7r/jVRbuK+rhGlRNuJdnUPpoXM/GqQXUxzgCPnJOkwTg9QhtOtJPb6PK7yhdscV0jABJbR+X7LzQJ9Wahm5cXDrdIDMLme0n10upWJ9bWFrpmFL4GK+3i80cmV+LglYO5VMcxkXMQFuefcz7suqaeeUU=,iv:hCwLut6ZardYXB4Ten5MI5kr+/iYG3f5Q0s5ZDJ3FI0=,tag:DYxIYyYyU4C+N2dyFeLh3w==,type:str]
    version: 3.13.1
