apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:EMtln2SsTODOIH7FKvfePenOTQCLYfbkL07LeYDlEEEl0dSX9W0SLDoPKz5jF8gaTU93o7V5QmTe7D+WNYzH/bpQ7MHsab2WxSdDm7HsIU2WRpSeOxICE+R/yHwsRk3KoDCly3RR5hap9ixLYCSSuQ4cuqv4/aFOoJ+DDQN3oEzlOnqHSYs0rCGWf0qjopUG9RPM0vGnKt1BizUni1t57pY/p2aXtrU5/jaIeAsPB/qtu3PeHAeWI+CfnK6mmC0Sq5oJv14XbSKkPCkjIhDfBnjv8CWk3Yzc77nho3yvkIn3X9WhVxRa+SzA5YI=,iv:YiAiIQfvA0KqQYuHqBOjQ1O9YyKCx5B85IfPV10Aybs=,tag:sD9Sk2PqpY3NLcS2aUZ0ig==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1eFhKeEZ6dHlGaHRpTUMw
            WnpVQkxkcUVScWFyMWh0Mm5ncmlZVVR0M1Z3CmZGWTQxOFpNVW41NkNkUlVrWGxU
            ZzFIRUFiNmZDZDIwM2VuanhBcG1kWncKLS0tIDNLcmZPdXNaMkR1REpGRkhSTUd0
            cHpxb0R3TWdiS2twcUdVOXZVa2FyNTAKM+C6BA9QG5phTovMTYZY6YHIJx5qpZ9V
            S36bt+e7IS4rMPQHcc1aJB6blGk53+NKVHuYsTIXUjI5OPlR8lhD5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T14:34:23Z"
    mac: ENC[AES256_GCM,data:px7Elmf8nDf91+dqidmEwWgO/QSlB8eEmoycv15y6hnTcnIpBLxvJmOi6RzwQ7NEwuHkEaE3JViMXc0M+Px9i0W5BaBEvtDGsNSgYTwwPVOIrJ9tMhPX2rLLjz1gHU9GoNctlfZXpT9/yCYNvCcOcLAHnHVD08nadgK0SCFqlcY=,iv:k6E2pQuBC0XiBBcVG0HUtHhraxwumIRLZbtZwsdxq50=,tag:uMhtcfaJ2fU6PP3SkJOdog==,type:str]
    version: 3.13.1
