apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:B7QK/Udg8Cp0nZ3Iij3Ery/lL+FpLofGaLWsBAEb3e/fEd5rUi1lDbPPzRVt0aLOgi7bgxa+iXP0gxIiGUQMAtMVfGqq5n3Nizm3SoX1mJAYcjq2ibyzKL4hMmAO2LczmwhIWZGmUm+jhOc5b68Tjw06XOn8mgJaXAr/3+/aGUdqv5/dHD8vpgU/le4GwwiNYlrZTkhuQRtRhHq7kXOs0lTKwbCdeL6zhAAUgGnoZsEnXp8151fDl0A+djPJiuDDYaf9VsnrMKWrB+bZiRLK/NJpDHf4LtabpM/aysh/Oqln4S/HuS8LqHjJ6jU=,iv:VpkaiKnd7OuXWRd1wBzUgY+6wmjoee6DsIUOOhJGEw0=,tag:lMDs5oqakVtRz88awZc3Ag==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYm5rY01OaUdINTVqWGlG
            bkdlNWxRR3ZWTnc2dVZwVUpJTmYxK2xWY1NVCitCSCs2ZE44TWtIODg3TEdHMGsr
            TW9WemsyaU55bm52bEI3VkdLMFk0eGcKLS0tIENrVVowUlJHVEdQSC9KSFJ6VWc2
            cVRZQjRtS0tFcGxuMGpyaHFlQ2htaFkKErKgyodGWYGfXCT+K/+Zo6Koi5QB5QyY
            t9BTsRdx1W59/0iXlV7qWRXrgvdZh2MuN+eBuYO7sVjNFPVsfziCGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T14:01:12Z"
    mac: ENC[AES256_GCM,data:b4gR4/SGgnXcDK5eo2+vgZbXGDulezoXDZcSYJmkL+T4EKB0ddEHS2bXDPAypixPtFgkmaFq+af/nRHW0sSnkRgEmB42VLk+CjLo24mQxpvYVcwKJH/CTwk3fe49wABGTsGPl4qQK0xcnZe/ZydcTsQw79oIhEXLZZWdjqo1sFs=,iv:sgmtxycnIg8FQUTW2MlVRUojm3XzBw2vaVRjIQuUeBk=,tag:kRTrLFCo6LpD0CxjBIJjwg==,type:str]
    version: 3.13.1
