apiVersion: v1
kind: Secret
metadata:
    name: gluetun-secret
    namespace: media
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:8yjRDDacxsLxEST9x0UHxHQSbdWnWwTCjMAKl0xY11RNjHG9ruFoQS8mvN8=,iv:S/S+xJ8G/FtoPF1+2lwr1N9rrrLYp5EWbWW3P/RPpwI=,tag:ERGKdpKrtbfkY8h2iwYlaA==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:j84ABY7b3OHuXXSaCsCX2uknTdtGGzgOLDXgJcX+4w==,iv:vPxfPOjRimNA9dB/z3oqXdqYMxX6na32UqeetMGyg3w=,tag:DJIUgN0h/zxe01edkxL8Tw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NnNkMVczS2ZhbTFxVzc5
            RFVyS04wNHZqakVHTzNyRmNRTWpIWFVkcUZnCjI5UDFFOXhIeUljVnN0WWpmTmdE
            L0s2N0xFekhwQXJFNTdtVjJOTUsrcU0KLS0tIGVxYndtVlpIdmZPRExQMFRJMHRQ
            ZTBSbFBkL3hUZGZSRFlsWHNHcEI1MHMKlFwyv1osYn7GPHiSsNQaEIOeJwapuSOo
            Zfq9fPjP3WgBmzFUY3pZ9wgh/lPaRQz1WRC5gumaEf41mfNfXcVwRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T14:54:42Z"
    mac: ENC[AES256_GCM,data:ysOYGHcDRbG9TG+Qliohd84Hn5cxfL6wxNSpIQwd1b/0hLpU5YbyLorCMmtMVnXiEzDB5yYttFEUddxYOEqJNMmfEpTcvQf8k6upwJxKASyUhUWwD1UnFrvgDuqLVP5Y4gLln1WdcTvWSp3npFctv/B4mhZZND/kfv+bV+dHbnY=,iv:0YXmKv5lsQ+eJXYeuQbVBji3XUvJyKXXuW1MFP/1cLQ=,tag:19zoJomdyIg+3nr7HkYGGA==,type:str]
    version: 3.13.1
