apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:FiJkc1UqVPwHPWHrzeU2YTZVuxhn41Dnnr8v0lJhEzlE/laf4UtdOzeN7mZt8YgSXMxKOnl0sflsfAk4u8bUMN1WL5XPa0wCzWO1Wh3AK+NNAo+1GDJiLu52SGNyfairXGcHXvdvYTVOEyoIamCTio+vbUu8E18JS2b+nZp+oH0yIc/+P5tfgoSTIXtl7ldD7rYUJk/qA9vEjHnzvcIwP4vWkfJe7CN6QWnQhk8F/Lk1WQfAG+oRGuv1VfE+awbtPUMF+PUS0RL/GHOivro67NfOGODfN/AJccMlyy8xtUolmgfIRKnlEGg/JY0=,iv:9TOGiH2ABeXZ/yrQqDl7SyestwxLj/zUPuaQTtEd/Sg=,tag:DDTTaprkSxWyEZevdvsesQ==,type:str]
kind: Secret
metadata:
    name: jellyseerr-tunnel-credentials
    namespace: media
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSFI0c2V1bDRxMDR1RXBQ
            RitSTSsyVU9pWlRhWThsRkt0U2lnQWNNU2xrClUxTGFiNG4xR2Fxekx1Z2hsNXZq
            OXpTMVFHTVVGc210L1MyQnd6R292U1UKLS0tIHVENEhLNWdxNFZlQzBIZEtaYkZL
            RTA5Z1BKZ2ZIZjlBNXZ4K2xZKzhya2cKVQzd+r4d4VZN5v5BGUFHvcXmGXSvv1QK
            CSba4G29PjD5LlIvqmzEp0DAoinmt6tAg3G/ochXh1o6YGLLHLvcpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T14:56:22Z"
    mac: ENC[AES256_GCM,data:vVNYhIqfBhfxzEaynbruxuuc5ZrPNri/V3yRSDGVml21miICOPgF1OkCANEjTbovQic/SsWQAuPrwQ/iJ4Ao+TCddsfyGUoi4TMkTD6XuaPMUR45uEBGIvbgyIVSbFpbFwycRIEV7+W7dvaG/19AH5osAfbTaVPwSM8BFXUz2Ls=,iv:93L14bCbJhOeAegcKyEJCew9HgDxSeLlgyrSSiWJal4=,tag:q2JOF80M1lpY4lWJNelfvw==,type:str]
    version: 3.13.1
