apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja
  namespace: vikunja
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vikunja
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vikunja
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: vikunja
          image: vikunja/vikunja:2.4.0
          env:
            - name: VIKUNJA_SERVICE_JWTSECRET
              valueFrom:
                secretKeyRef:
                  name: vikunja-secret
                  key: VIKUNJA_SERVICE_JWTSECRET
            - name: VIKUNJA_SERVICE_PUBLICURL
              value: "https://tasks.nohermosa.com"
            - name: VIKUNJA_DATABASE_TYPE
              value: "sqlite"
            - name: VIKUNJA_DATABASE_PATH
              value: "/app/vikunja/files/vikunja.db"
            - name: VIKUNJA_SERVICE_ENABLEREGISTRATION
              value: "false"
          ports:
            - containerPort: 3456
          volumeMounts:
            - name: data
              mountPath: /app/vikunja/files
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vikunja-data
