apiVersion: v1
kind: Secret
metadata:
    name: tailscale-sabnzbd-auth
    namespace: media
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:kv0/uIpeMYSdRdoN5EqIdxMf72gxrfdHJpKWKtpVHW36TOOTJ7aIw0pXz5KVHdgtqRv8NkCDGThXinFMLGs=,iv:xFppyzJ0jA8CKB9B65HxTfiDvGYRmMAYFQcQbeRp9YQ=,tag:Xb66fKeTdHWyOOOrYyq93A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaldyQnNndmV1NG9RTEx3
            dHZHMVZOTTV6S1N3YXpxK3I3RlhCTVlodUMwCnhEK2gxU0JoamY4ejI3dk5OTm5w
            dFdZb3RvSk1CNU5wY0tZVTFSRUFEZ00KLS0tIHBqQTIxdUVpSHpYVWpVd0o1b3J0
            SVI2b1I1SGJEN2F4ZXM2TitqblRYZDgKeZEyU5fBJOmNLx8yoeRTojW10kkcbi+D
            a6JiQHXTmPC7oGw7iP69p++kdlG56DBn7ySmDavE9ylMPoIcxHvYMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T13:57:13Z"
    mac: ENC[AES256_GCM,data:HnaOaiGBGnVIDJw8wor/0WpeUecaL21W24f98wqflcNpl8O0OWwFtpx2NOlApGBZR4JlS1OWEmymKfsnEmaW/73m7u4SRdPjK3ECg+Otbk4M9V5Z+9bCrY8AuaI80HY2o3QhcOZ9aK2HL4jbs5sZ+Rx2ddcSadOfCiLPFY2q/Wk=,iv:wU4lCsIuD/zTOjqPGJltJsGVocsHVexKVhImYjkEJRA=,tag:bQYJGHmHO5WI9d83n5CEhw==,type:str]
    version: 3.13.1
