apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: tailscale
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:9JB/nOZO4K/Xl864Mihov3dWgVa0TCcnJxPxLv/OHS34zCtcV8qa7MnXh6L6Je7xGTzE3c9G+X2Un+yR0A==,iv:KENEKpCoAuavlzoh9KxRMgo4MVUO4xzorVwzmdYSMRQ=,tag:beogp0A6ixRePBdbbUOa3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSa0ZwWGpQdzdrdEk5ZFpO
            cndYSFlJd2RJSGc1UDVZTzludEZ4dy9DMkhvClV5QXl2b0xEYnlIMTdIUSs5aU8v
            a3NSTjJjazBaMk9nQUpISUVUKzRQb2MKLS0tIDFhR1M3cDNQcytaOEVVdmhqZ2hY
            MHZ2ZERhYzVuUGR5WGdmWmU3a0FUNnMKNJP8JPEHVnV7p0IbUC6tQMdYPS9IjU91
            DQVpSQLn6prwInxDUpvdCGoCgzBzSJmyIa0kK0+PeaS5t4/7O3fLWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T13:26:23Z"
    mac: ENC[AES256_GCM,data:MYA1u5+7eeXsbeQQqf7nG9PHPFwy3jkPPZCEHog735H1g/EnH3HJ6GA/ADBfB7YaSvJvKoxRhbuRIc8qMzJSiYfu8MXTnOwT/hpI7UwN/aceycfqOEQSVuPdNGLySpCKydYL9g9iWVQwYYShnUYkPFe6h32wMKfwueFWIDQR1Ho=,iv:t70m7AotQ8pl1TxvK6btMiEhCknSRBf5Z0djTSnrXVE=,tag:/wbgtXnVked11hpsMv8pbg==,type:str]
    version: 3.13.1
