apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:8g/25YuWZPPQ0KpH9rHeX4Cmt+MrAKtXngfwFG2LpIBOcm+hRtSn6AludvLAFmelCSDzo/qFp8IgzuFDTdR+kF1vLcAc6dxXNsx7csti/FHnNYzQCvHhxKRJ8CoxNPlMJYK5aTkI6N+4OBauNMIlQcMNsrvuQ5uAQgK/5tjAlyR5nwbJ0P2MFwzE6Els/rljM/91i1/vRNLYnS/Wpmffty+UlgameKoqSaiEwpz3e12uGZH1svGtHpcfw1ZN17zFR5SP4ya5tHP3Kc1T2yICbBpVv3o34RDP36zYqJRQuMxhtdNPva/5069kVlI=,iv:nz2AAAusDHwBxHAe3mjgTx2T2TH8hQbPNMy8mUz5UWY=,tag:4PCTEHF6MNAcORxZqO/Q1A==,type:str]
kind: Secret
metadata:
    name: filebrowser-tunnel-credentials
    namespace: filebrowser
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSU43VnFsOEFWd2pmSXpT
            S3hSeFUrcG4zb1JDSHg2WnVpTDU3UGhwRmhvCjR1TVVsSjk0enpzUDI0M3JXaWdS
            MCsyWDNtbkxHSUhyUjkxcThHemhIZlEKLS0tIEJjRksvU1ByKzRVVFlDc2t2WTEr
            dGJoTHdYMFQxaEg0eWRPdkpKc2haRE0Kw3nE1z3ZdUqTt04PIYtldlcX6buG+wCI
            6pkc2c2fQV+i7B498VlWZj76JMwP/VYrWEVWeGnSABrfjimKU4CAMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T14:39:39Z"
    mac: ENC[AES256_GCM,data:NwU8uWsLoswjtVEiP3x94LbpDAT6gDl/qNHFPIVOsA+8/cdVpEoYKWJhQyhLa/g0EMEfMZIy3tMqnujquBDWM+WYxF0UoUY/sJzW432PKEPMODC9pEttHQOfbZthvNMPw9FsA+1AdB/DmtKH+ju2nnl8eivOvoeM8BjpkIQbR1Q=,iv:AdDK76Dkg454DUbmxCS2C0WvulUDFdparquvg6AAaIE=,tag:bos+FTu9dHsFME6ISmN4Aw==,type:str]
    version: 3.13.1
