apiVersion: v1
kind: Secret
metadata:
    name: filebrowser-secret
    namespace: filebrowser
stringData:
    FILEBROWSER_ADMIN_PASSWORD: ENC[AES256_GCM,data:LzgPk3HmXDQ2MRd0,iv:x7YYplYWR7X25jPuymgiBpE5VtRsr4RlFs1w9x/YHnQ=,tag:nvvUsf0Ud/XbRwuwxxNe4g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQ1pXWlA0WEZrbllWQUpI
            ck9hc2VIVGY3RzQrWFpWL0ZyRy9yVzJUbmtRCkF1ZGl0TlpXc3ZMZWNEQk5CYW9W
            NUhDZk55MDUrQjFRZGNEUzNCNDk1RzQKLS0tIGlwbVgvejRCUG5uRE4wWDdVMzBM
            R2piVzYzaWdrNjdwMlBnRDB2bTlUR28KOS3JMehAE/68ML5XpglX56+OQFxTRqpA
            qUrdhkj/SiYTivehh2JRYC01fJ8Gdg9EFFI/PTWDgcVSCs/bQ+/fJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T14:50:51Z"
    mac: ENC[AES256_GCM,data:V4ehv4fcrWrxfnc7Tt43efvqCu5Yf3hGGKlpgZT5t7VtNW2gzah2XW0JVACEo0ZpY8I1uV4yNeW+zJh8xVwFsNzA1D612LND3HxyGvyBI9dV3RqvTgOhFYDIhl/5EF/Oof/JqEzsEK80usHJCd0Z6PcqMTh0Rg6+gd9oiAee/SI=,iv:R1Tw5RqdYYOctQSupbPLer6a2acQ069jJd/f2Q7iQ+E=,tag:qH/OJaZFvVJ0MrVko36ZYQ==,type:str]
    version: 3.13.1
