apiVersion: v1
kind: Secret
metadata:
    name: mariadb-credentials
    namespace: mariadb
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:cOFwcLdNkUuynntw,iv:8qLpv74bcfD0E/zbHENOdnRNhEfU8+E5/1RAdFq6SxY=,tag:86iH5Ci658t5aAc0Ve0I9w==,type:str]
    zoomzoom-password: ENC[AES256_GCM,data:HRYMUWFPpi5LlCt1,iv:Lwc3JXnjmZ0G+/ILmTYg2HZQ9RFokqzUHrsV1giu/tc=,tag:pJtGqHPbu/+84QoQ9opQVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTjZTSGV0Z0pxbkZuUHZv
            dnFzQ202U0daeDJWQ242eFNtSTBlQnZNblQ4ClcwNjU0djVDVWh0dE90NVFkV1dy
            MzYwUUgwaHRLdFkycnNDV0hXYy9FUTgKLS0tIGk5ZFFCajAxcDFPQlZ5anJPeGk4
            eXprR0RjRklNRkZyeXRlUE5HTmtCK0UKCdwtdrGCK/OPyF6vr2acIzdR5wtLDRuk
            kWKkEnkSlQAJ2w2wnbH6380ekq3o35z9GIsgXfV+pNljFfS++splgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T16:17:29Z"
    mac: ENC[AES256_GCM,data:1HZKRR0Lhoh6mou9LEIbPy5V5kFzUx14XTl6Rw+Gf+PjQRDLBy5eg5cfOGhZC6sZHpC8bNHL2B9oVFOCydFT2CQtffYtsr1WxulBtKdxMtuhzVTWcDI7NLB4GxGcwS13gwNfNO9csha98xO/l510UXFWuN1czivGsws/PhU5WWQ=,iv:iQiTZWXXZGs1ufaMaD3ycfAyx7uIvPW0mdQf3euxc4k=,tag:jWU6kXNig8SUSQeb2iqHwQ==,type:str]
    version: 3.13.1
