apiVersion: v1
kind: Secret
metadata:
    name: mariadb-credentials
    namespace: mariadb
stringData:
    root-password: ENC[AES256_GCM,data:M/6NwnZ6Q3bJPFQi,iv:iYazoE/TpM+TzFM8LCoToZ1az0pJ2771PbCDhn0/aHo=,tag:U5tLt/eqE4W1l/IhHDYvzg==,type:str]
    zoomzoom-password: ENC[AES256_GCM,data:HRYMUWFPpi5LlCt1,iv:Lwc3JXnjmZ0G+/ILmTYg2HZQ9RFokqzUHrsV1giu/tc=,tag:pJtGqHPbu/+84QoQ9opQVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTjZTSGV0Z0pxbkZuUHZv
            dnFzQ202U0daeDJWQ242eFNtSTBlQnZNblQ4ClcwNjU0djVDVWh0dE90NVFkV1dy
            MzYwUUgwaHRLdFkycnNDV0hXYy9FUTgKLS0tIGk5ZFFCajAxcDFPQlZ5anJPeGk4
            eXprR0RjRklNRkZyeXRlUE5HTmtCK0UKCdwtdrGCK/OPyF6vr2acIzdR5wtLDRuk
            kWKkEnkSlQAJ2w2wnbH6380ekq3o35z9GIsgXfV+pNljFfS++splgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T14:14:36Z"
    mac: ENC[AES256_GCM,data:KqiAVdn3L6yilxsSmBsgQbDVnnm0+qTk5J9g7xyF/tNFOviAEgcZE9ov1RoCxprwn0Gzd/jBzYsRBW+xmFPhAx3LRZ2zE4/SlDu3K88yYUKda3LxEi0E3Ia28XB4yHLwfQSVS+ofYqlb3SLO93TdGkuuieU2vqRv2d14QzzKva8=,iv:nm1G5XSEhwXhOLw+REXMaPLaBECTu1ZO/LFHq24vLLI=,tag:beEu+NvVMssN/8bEHfQltw==,type:str]
    version: 3.13.1
