apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:eAaBr3k+c4LevDKwK89+b5LhpysX15XAa1WRR6EvAph4LgRyFSJ0QNs4OFvPKW1Xhhw3ce8blrSTCF+CsemMievpg1qyiu9aN/cWDvMaTKAuy3Rvxgx0kntnX8vMywimteTxC+SVSB5cZObtZrtg05ux6pZhZEpmxQZSJP30aQcQ5tDGOZEQBcyLOqcAbza0yG4LfsVw0NYOZK9Rz7JcOWVrPio3Xh9AYSGb1p3VOTKSPjE7ILbWF2xMyvNce2FATHDZWIzWOLqyK9j+mTnyADtKn3gCVRayEy1CYDWbaOenydmmS3ieX2mfsyg=,iv:B2AF1aRUHjoo2J99rGG1qCo+BaD8FcEAp4QZ4dkBEjY=,tag:Wo4Ap7PwCr51Od9N1i5aKg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucmF5Q2ZkUVBkb2JmNURJ
            a25XWGc1cjB0MXFEcHI3Wnp6TElTazdLd2w0Ck1seGNjamFtSStaSitxcWttUzVp
            U0t0Q2pGY3lTRStiNDNva2F0b3piMkUKLS0tIDZ4OUx4d0UvWUNoMlZLK0lIV0Fp
            ODVTejBESmkwcnlaWmtITlhTdFRwVFkK6ZYIYbOblyV0esHAwATUXOhs3lYABTDA
            WXDgfsaOzgfU2gKQ6Xhj85JM5FKzCyvv6hkoXWn3sdzn6l8+G3zNVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-21T14:55:20Z"
    mac: ENC[AES256_GCM,data:l6VM5Np2vfZRF/6PDtF2OsNgS1KMHtxeZQ3dQWRi2AmMZFC2JYpHdRsrhN8Z493PB577SpEIFDnYM7vn+rakN9knC0r48P/JOWz4Ai2+mpAfej+03xDRSIGP1a38LcNY+TB6c8RDfjj0CZwXTIzbQbSbSh9eWQH+wg/achHJiTg=,iv:FbR0eYSeJ2w+g8sUKWjqBux/7BlX32MVgNVfv5p3nYs=,tag:eJ9NZiriQu1nVrQ2KJd2EQ==,type:str]
    version: 3.13.1
