apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:3k8du7iUbG0=,iv:7GJCE7de8BjH+DfLm+Hsz1QRDKr2luydyUGMoM6XdFE=,tag:gxcInzj22Ki6mWFp/zi0rw==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:j2FuNliTEl7jO6MpnnRI6w==,iv:0gw1OQXve28lsViauNT8EuGu+oTYSNOtckYQUUad9vM=,tag:Q2glsfRFpKpI6OWYME6bMw==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNm1PdHNjUm4wRm9LUDQ3
            MWNScGh2Y0xSNEFpQUtrczRHdmJCODN1TkQ0CnlzMlU0VDBKUzk3cjRKN0Z1RE5Y
            bEUyUm14UFFQdlh4RFpSdW5oQk5GMUUKLS0tIEU4ejlqS2R6Z3NTUmVpbXg4UGhG
            K2h3dTFQUENMZUIvNkdlVDNtQ0Nld3cKn46t8q0qywBDa5262TqvRvp/b6GWooSY
            NHKVLZva8mMjgwEKuOMfdZU7M/XW6PKK8/Py3Pgx/C53AVsZIs5Ghg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-21T15:04:55Z"
    mac: ENC[AES256_GCM,data:+c2tK5ldq3BFF8JyRD/bNwcKO0eMxrEW4M7oLlzmzpD3bdwZt+MKSw3qIysY50tn8FhRa68hTx+CwDjU/fqwQiNANPdfMNLktxf4rWqkO8ZXQMRYDF4dwmQ4SrgtvRvYyLqlji7M0g5RjNx17hPquvJpI9dz56WGJF5EG5C3G6M=,iv:fLg6/i2joaeTpB8zirdXHhTH7FFL3woeWmFaUuoupVs=,tag:NjA+Um/UxV9fHwlhG/qvRQ==,type:str]
    version: 3.13.1
