apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:tnwwtmvsWZ+aRsLjBuYOsDy2NED01Nf4iNBvSHoZR3Mlq5bJ84OFIabasG2ndPqp/YM+k+BeQ/KvnSF4W5LcC1V0x3l036n4vFJe5MlaxX5z4HpYu3FonmEWneZW1dQ17o1Phsn0gsa3q8xCoZpziQFJ+ZBrG6uZAEIgt2+S8YmFQRl01LAdMCikwHogwjAVXI0ot+b+SKbWdiKBGSGvp/r1nWr3U16Rq7OXlPEuWML2nOP8F3ZKmSBfped7XMcX/Gg34vpJEwPKJAJOaUtpKWWOeqJ3fo4fQ923CET0Rs92Nb9FWa7l06Zd6nA=,iv:nzrLS7U5HzoyUd4JCCB2Yd1qb9EVO86V745qZl6pSDU=,tag:lcMyDna8KUypRyqFLV6zgg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: vikunja
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodEdZMkFBblptYUE1RFhx
            OW9xcklRVmtuU3JvYjJVbjVvNStWSkRzZ1VRCmFPclVxekorUWUrUlE2VEZHTVAv
            b1FkUi9NbmtCUjN4T2N4Mjh1Vzk1MVUKLS0tIHBRdEI0bUsvc0JKanJRenQveFlG
            OGpzR0QyaTR3cVcyVW5wZFF2RG5oRFUKL13GmY+CAh18gsGVsL8j3LItsYBJQI1h
            vTWvEoZodZws+ku/7/C08S7xOCDadYM14OdZshr487AFk5DXlB8TrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T13:49:17Z"
    mac: ENC[AES256_GCM,data:ZgeVhYHZbMVH9S4TMrdKGFKNZSk3mxpbu8Xa7V+o3WNX4U/Tbdqvw13Ig6GcqC2vbsi9PRL0opsb1F235nR1gsViocLSUsR7dGK5j6NziUzOkbKvJJHOJH082kYAtxdScwNZO7FVT4YWd0QEBuh/yJYLaTgb/Fva+Fzs3jSuvhI=,iv:6ykmQW3IR/NeYfYd611KhsSQ6SBkrYgH4iyP4KW/D/4=,tag:kPS/1btmiYiI2JTpOl15mA==,type:str]
    version: 3.13.1
