apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:a9NbTR3TEd5evDdnkHPrS9tQhksEDBO8jDIr1qxX/7zH09/wAekN7I7ymsCDDF2zksQlYgD/88NCFWlWY9eeVoR3Z2JarrCF8IoIT4dSOmkM8gEuh0GAbYmjOlUJF6P7BghCCanXKIXCMoYKrcMciRG9FSJSF/J+MGzP+bTat2H0F0aZ2EibZXUQpDyveyGaGDhr79kEncmBm6uBBcBpIkLoqf2aEe/9PC3uT1ViPghOExNQ97NQDaQYmjGHwKY36A7047B659NvRBSw41gerjLl1VGB9TfCQi/BT9MYjG6ffuoSwC74FGQBWyo=,iv:5U+pNMenEg6F/eHXUZKyiTI667LBrYVPadC9e0w8Zi4=,tag:pURtIMWfYSM2yUSQ3KHOaQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTEM1UkpVZ3VEZEJSSmc5
            eUtoaldOazVHSmEwY2xrQlNnLyt2K3p3VEdBClh2TjlmclBwVUNYc2ZycnFvZHlt
            VlFJckNwbTkzaVNrTFA2UWtHS0JNSkEKLS0tIGdtRytYa0tZb2d3QkhLN3NBdm1w
            VzhSbGp4U3ljdzA4dGtJWWZsYVBtY2cKKoX4Kq5rpcfNFoCth+Z2ie/owD57t05O
            rgLw1Y/3fq5CgE6cozOlmbwX1rE+KVM9/Y4KfCsWDYWq1KnO9HuYiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T13:22:27Z"
    mac: ENC[AES256_GCM,data:SQxyRC0n1Zjt9wI8vVIvu0HL2I48Abt9FLg5RJrtlSf9y5mHRkeZY1EK02ZiIH5Jrw/myT3gKar5duR0mDTzzxNADpe7HBkXmgCRMVON4VlYYn8WGgXauzjseGVW4BDJTwbuvfs6kGst7EAf5uA1beY1fEewG66Xc11aKdX5MZA=,iv:qnQhkksebxkJ4ldxSS0P5sUdSng6NgOP5yd0aVL9/40=,tag:km6zldgR+jXr00b+YT2suA==,type:str]
    version: 3.13.1
