apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:L2AL6QblFk+bJU1E959RDPkr2W1vV1eoFvjCC21wRILojZ97CxfwY6UxjkClMILs9OKUcnu5hcLgc9z0vT7wYukB8ToN3swjxenqoWwtafa/Jcmp4GUUDWOSJM/kS2BThNfksvx7gPvED4+YwV4GRzkhDmQMh4LWMZ7eoLI5aJBEkkEAULZkfuTD/PwPzpru82JSo68+KjJ3KOcDutW7THK91fUtzzut7ro3TTJfqhrBRGq/vxjAB3NOWDvYQRhoqF8sEZ1XUozUPhJd3Kdqm6VTVtK263LNFRH9ibJKBL8lpvsxAcOJwgvrezA=,iv:BhahIhupt4pKbBdOLV9mNGTt2ljjjiiZ572oP6Pksf4=,tag:D4g5A4zxP14zlP+obKgUyQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: vikunja-tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNUZiemlYby8zY0dOQ3pt
            OG5FSmVFSmNzMmkvQS9SYUxteWdyYkdxR0I4CmFYVEN6T1krQ29LbzljZlhDV05p
            TzA4UnZQc3JUcVNaK1hZTWJPdzhUM3cKLS0tIG16MWQ5eUZoSnZwb1d6TGVtbzFu
            czFWUDVabWQ0UVBIeFVmWENZYkJ4VDgK/vgN3OSUqyQ7XHDIPsDFZTNNoarxuKRb
            Orq4V/WGk5No8R3qeiAEwXpNHNWaNF8NnhRtC2P4ISeCAEQKUv9oMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T13:43:11Z"
    mac: ENC[AES256_GCM,data:HNg4YtJV0t/fCAtYkn/kCflFrY7CgyHzqROOJIABBHnKPPxELEcirBcLGwYFFer7t2nKr0o33CwdvVSA/GSpdQ7O7gqSUjx6igVW2yB4bUho7ABlBdNi3RLg53ew99mm3ixiQkBa6i86VsL7Dt3vFGN1yeyDFrb1Q9MCpbIL++A=,iv:XGoVxOYJFt4D/Xk2WiQa0Uy7uDjlVLNvargHtjFABhs=,tag:BuPi/tbHfhrlbKWARLMiYA==,type:str]
    version: 3.13.1
