apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
    namespace: vikunja
stringData:
    VIKUNJA_SERVICE_JWTSECRET: ENC[AES256_GCM,data:qeSN73gOpEm4uVKkCn4j0VCDLZNSfRNJFB9Q76GhpsEhecM0Fx3Zbv2CIc7sTHhZFcqMY+tRIgcfmXKJpXkoGA==,iv:IxsOB1aqOwIMGtqkKN8gnrLHHtWYIuLtk2YNw9vyYLc=,tag:uPgIqoATektOTt33j4PhDw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWjBDVmNWL1JUZkxQOXhO
            VXNUc2UrN2ovbmk2dzlYZDQ1ZURmM1VvdFU4CnQxTkZnMlZUS2Ezbk9zR3VxVWtK
            SnBzeUJ0ZytwdjRvWE5Qb3ZzMGp5YTAKLS0tIDRhSGdqaUgyMVFYN1owNHVSekxU
            c21hdHdGaWhEdTZGQTJqcWlvUFJqZm8KIOAAlxLCQRrRFM7qU9dAXz125tiOkwJp
            H9ZXTgKD/mmPLseLJPih906gePgVseFSQfURNW+s6oDkR5+rndBBFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T13:19:39Z"
    mac: ENC[AES256_GCM,data:+M1IeRvT2qTQibuMlbGHIxoLuWhHq8JdjU9hQMjjw/rfssriGIIH3R/bWSKWyxKPsd4nRjLGz0/p4oJ8V4c6NWwjMyVBMpGDiUjnTR6Iwf4W3PStlMHEH/8qOgH3L0wt5w3+PmkrdOJhMrqONG8OBNhXWry9JenhrG43krCYcZI=,iv:sXn+ih7QCpMacjc3DjIZZocF6ByBzcV5Ok3Qv3uhkL4=,tag:hhjjNort0g9H/vtEPSSlHg==,type:str]
    version: 3.13.1
