apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:MpSgf0lLHvxBjgCK9GFGFd7nO2cjp0Ot4Ul1WCZmOr2wJP3RIQg6UmVmqzZ2/nPR8QsQ7hZYtkyOVYtHzRYdxq2xR0bSYttlpIxHPRRA/ZM7/J1NkqTLHnqTr6CdV7yl3flsOT3TqhOhonr996MIcvNd8I9vw9J4FXXW10IfzFYOE9OQagYJXJUawtkRtesHXNKOsP/WGkzO0ljrrHEVJt6cOUPuTGGiRiN59xwkx+4pQlLtAFZBoNF1mpHr1JaaAJkGRxUS5InUIuQjT2ZdijChQDjXL7jpf1motboncXFzUUVmvEFHlRtBVYc=,iv:PV65hia3W4q9g8gd+GQQ8Mo05rLe81zdZIbzVY6QBQ8=,tag:04qmXrhKLop1/kwfaCMpDg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNXQvajZrdEszZkZnNEd5
            QXBkdlQ2aVBqRlBZWXBualY5N2UzK2o3VFJZCkpVZkFLT3BWNjlaQXBWQk1vV2w1
            WEc4RHY4RDFXUEFaSTdKZTZuUHJST00KLS0tIHd1MWlObkQxcFJrSDhFWlcvVEVP
            R0NDK2dHVnRJMGJtaTNqQ2RFMkVVVjQKhjcVCJ72ZOG+0L7RYrkBz8FNTBSKD5A/
            0AGhKuglLsEXKt6ke+9WBkUDnvvsjhrq7eHJmogTlogQy7vo+XsEKA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T18:08:40Z"
    mac: ENC[AES256_GCM,data:Eb/j3o38WrC1sofPt8Kabp2HbDgId7rbYKx4dJGFBXHKBRAKWwlDz5nrI6CuYDi7vBrytvu77CPEOnbBwvehniqF1/3GJWQduJjBDCoEZvcAkln0NY1c9SVqPg6o5j9ULcFCVkPFg3nH8mOYpD/AADF8fjFNJGjHl0qS/jIprns=,iv:bB5ea3nB/hLG9fPFCOA7SptSOC6/fzpcD2F0VIn4knk=,tag:LnhWm92ZYdqxcZdIMTgeRg==,type:str]
    version: 3.13.1
