apiVersion: v1
kind: Secret
metadata:
    name: hugo-git
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Oe9VIw==,iv:RUo1C5ZxmEulbmRuW54A4yfFIBN72Jy2232ciE6DO+8=,tag:czks3wo+jdpXvRSRekp/qg==,type:str]
    token: ENC[AES256_GCM,data:wFPnbE/av3QxqKMd7Eo8QfFUwXRE/hrLRfrtMShJWh99GAf4QMjBRw==,iv:IuD5SePZ4/XuY2VzHO+DdBFW6L3EcghlVgUhzbaG1dk=,tag:sJY2/xsIUh5Wz0APu5UxrA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbk5XalA4TzhyaSsyUGlG
            dVpwb2x4WVFlSk5DNlY4M1poVy9tTnFIa2xFCmNua1N1V2pDblBtYjE1aTBRNURa
            akovUFRYQWsySHVFdnVvdGIzVjF6SEUKLS0tIE01V0V2OUVBNWFXSHJZQWswcFZU
            NTNtcjBPQUJRMXNuOEFNakZwZElRS1EK5wFjpNVLQ11DJJgnJMskc+L8MS9lIO4E
            Lj838qHSxdx8zrqMHbTq2HBE496qYp85IBk+qvepBiW8xEod3dIl4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T18:13:33Z"
    mac: ENC[AES256_GCM,data:bJuXpHJLkIJvTn5Qn6B7+OeOghWlgVsZPc5N0HPyujJzBhKkpQpBQsyQ1nr7av0Nap7ANd4ctxof4OVeE/nniURlL/n6l+cK/c651xz4zAW3WW0KXASN5c5e6VO3Aitso/KCQH/O1H4L9f5Rft/e6xjjlsBkWI1i4OI1N19M4b0=,iv:AYfnzkprqUH4TzjeH+3ghUIvjEz/wjCX0BMyVuBawMs=,tag:ErCrr39+EFAqs9HdybSNvQ==,type:str]
    version: 3.13.1
