apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      containers:
        - name: lidarr
          image: lscr.io/linuxserver/lidarr:2.14.5
          env:
            - name: PUID
              value: "99"
            - name: PGID
              value: "100"
            - name: TZ
              value: "America/Denver"
          ports:
            - containerPort: 8686
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: media
              mountPath: /media
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: lidarr-config
        - name: downloads
          nfs:
            server: 10.10.10.10
            path: /mnt/user/Media/_DOWNLOADS
        - name: media
          nfs:
            server: 10.10.10.10
            path: /mnt/user/Media
