apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:comV0a+k154yIN1sOD4J7nbWWSu24CMoZ9TwRy1vMSvRTj/HIQQ1iyl/gBPJLC9ko30PQizf8fPTjNMfb+P/DRzb7zFL0tQcAdI7KvDteauBwzm7erfdNDU8Yn+xdz1MBmzxp0kQKeJuuUqsCChlS1XuEqJQJIAvuyc/DOAhmgJRNUErFSOSlOg8sAeuavcGPSF0DcHuUsAds1+YVk82AuJG69MjXPocPYMphCHkRbYRTVgsF58STeyb3AUlcQ20vXf/73M2dO42ABAdWx58fgeaY7gx4jbGB1F+BlQhywhGBVApCm2WLVySEM0=,iv:ar+OyX11qjm6S17dKvMNvgyaLg85nyMMBWRlQz2WxeM=,tag:3pxZKmSS/G6Iv9vW9bZDeA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UFJoemQzVXNEMmdPTzZB
            dDlOZXJ3cGFsTEdBTnJCalViVWNwWklzTHdzCkc2Z2kyZnNyZVVwK2pkRjA5SUxn
            bktNUlNrVWZnY2IrVFJtYi9hMW1vVFkKLS0tIGpLUTNSUXpoT3FoM0dMNE11dWZ5
            OVZ3SGplQi9ZWXdzakZBT24rMGtYSlEKFJnAcAu0J9u/L9PtMsp6zfIHDLTcEly/
            YoT82Kn9W5h803yfUpke4Im3/GlGEilCFdCJjD8sK2TQcqGswd9Lng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-23T01:04:54Z"
    mac: ENC[AES256_GCM,data:4l+iCSep97kgkhsITrL0HrJmKyzN+WzdBTUhl9kBmqe8tW5ooCzjDB2FtZVF2I0gcNq5iGAR6rqZcLEP5onaomn4sQn8c39vZZLnmpb1X2TVSyCWY6X1Vkb3RQaoj+4HtP57+yb+udSgKMLJitcS2bKf8hIH9gXO90Aq1U/ZIJk=,iv:woh883bKA8P1DI0AbdsUzAqK7pVM9LATusONekCG0xM=,tag:Ips7T7sgA68PSSdktO8cDQ==,type:str]
    version: 3.13.1
