apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:ZpKVB9JHfBWB1hTwSypENKsZqVwS2qGC49sggthiCkoUe/BeE4V5JLEqaerkQVZ23xQYpNegm89EREw9iqzgQhKIeh0IL0/SBeQXdUeB/A1VGl6eHDyQmiDZglmcfuDXeOIq3z2hBynxckxnYDWBTXeWb3ipZK9F6DwhX2Gj0t6lwGRXmHuPQyRtfq6DbdQhH493lonIxHvOrhDQ5W9QLpHigdZGScjatMzGhGemgMR1dI1/a9STyXQ1JIQRQXRNooLqyVaQ3ROyJb00b2tIRP53VL8KV+q4mYAELFAXuGmdjeZRmlCSvJYhGgQ=,iv:vyePjijoRfW3UQY/DozTmZbx/ClXzZJ/mIrOOzRJZMM=,tag:kPoKAjaJhCQTmKoAkeo/Sw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZzZCTjFlTDNmcVBlUWs4
            RU00VXBBRlQ2ZXowQUtKMkZVbHVUNytERXhJCnhhUHVRMnAra3J4NzNhWnNqZnV0
            dDU5TXpXdTBsNEhOUjA1RFNocVhnNTAKLS0tIDBKWFBKd0x4R1BGOW94ZjFHRVdW
            ZU9jL3h6OGVpdUhGM2ZqNldLc01jcVEKdbUzOI2ncCkJFyOIYSZGSXjPQ4jcSAme
            NYyTDz8VWabNnvjWH+KriTzG4snJ6WepQ99u4TKlNpKvJEPmbLjenw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T00:36:53Z"
    mac: ENC[AES256_GCM,data:4hIoP2oLnua7L/cO13dPa+ZO0ODr4TCbsezDXYoY5YWrm7eie3q+bA8/v7eVTdYdUoPUU8Nfn5SykgeJEM/L8KwxF+yic7cFgwc7oBB3u3ZcPBsS7qrpCDB/VL2zDDTCq2Ts678Cjrp6EO3GioD2E30QVkvFwEydfHzphh4P9rg=,iv:oCFX7xA96K4KWKvA43pyKqtF5JQNhhKal554N4aIzzI=,tag:FoUXBHBc9clCeRNs7WxHKQ==,type:str]
    version: 3.13.1
