apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: wordpress-bridger
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --config
        - /etc/cloudflared/config/config.yaml
        - run
        livenessProbe:
          httpGet:
            path: /ready
            port: 2000
          failureThreshold: 3
          initialDelaySeconds: 10
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared/config
          readOnly: true
        - name: creds
          mountPath: /etc/cloudflared/creds
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: cloudflared
      - name: creds
        secret:
          secretName: tunnel-credentials
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: wordpress-406cruisers
data:
  config.yaml: |
    tunnel: 1389717f-bc2d-47ef-b196-8ccfc9cbec90
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: 406cruisers.com
        service: http://wordpress.wordpress-bridger.svc.cluster.local:80
      - hostname: www.406cruisers.com
        service: http://wordpress.wordpress-bridger.svc.cluster.local:80
      - service: http_status:404

