apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wordpress-bridger
resources:
  - ../../base/wordpress-bridger/
  - secret.yaml
  - cloudflare.yaml
  - cloudflare-secret.yaml
