apiVersion: v1
kind: Secret
metadata:
    name: wordpress-db
type: Opaque
stringData:
    WORDPRESS_DB_HOST: ENC[AES256_GCM,data:xGu3qPR02yXIO9GBiwchq4Ur5Q7dEDNs4+VFIRovYVdV,iv:j6bDsjfgxdOAe9ZLe5ofk5Kjvgrkr87oDVY79XAG3Kk=,tag:xPkpVokv+e24TCExb1hraA==,type:str]
    WORDPRESS_DB_NAME: ENC[AES256_GCM,data:5WykJIcAmJU8o56OfXE=,iv:vImRYig+AzOu5RK+BlqV5/ctqC7fUgwZm8qNebI3k6I=,tag:FizjlmQfIN66MkDlM2Yk5A==,type:str]
    WORDPRESS_DB_USER: ENC[AES256_GCM,data:B7z8dP9nzA1B5Dr6DfSxEw==,iv:DU8ox888a5HDhK37WOatwoON31qcbEH+2sxDLID/Exc=,tag:iw54CdtxhJRKL1eRWa9Nfg==,type:str]
    WORDPRESS_DB_PASSWORD: ENC[AES256_GCM,data:XVgJghpLhQ4aP13T,iv:Ctja6l9+Hi1m0H6fSRhHmkWF09vAc3i+vEunq26wogM=,tag:hTAZMHOYYD6Q6NAUeaVQaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTnRYNlhEZDhCYlF3YzN0
            RU5pSU5vUGpyTDJ4WUE0Rkl5V0ZQaXo1WXgwCmgrenM4UXdrVm1hdTVUL3RvVlZR
            L0JYSjVnTDZPSVNMQzQzeFpUMnAvR0EKLS0tIFBDek5VaHZTdDNqcXd3WU5vMU5K
            SndDRnIxb1d2cDZycm5sa1NvUSt2YTgKaCSfhV0Z7blKwd2OJB8ym8ywCNFZEI0i
            Ue4rjbB+v4PZAEmfJczIs9vvHfV6RI5O29p73n1jLHV8E4OJQmOfPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T00:41:36Z"
    mac: ENC[AES256_GCM,data:+Cph11ZCNBqNcApWOYeXF78i+gQOOxuiG195SM90kONyID0T8MBsNg05sjnnNLXDO5T08WGaZp4HlpHHvRO0VfaOllKUoZ13Nd648v3EYZWvBooF6hcce2o2+shK8ZK8t/ftKJw7Jcuyn3b78EW3d2O6DndUc2NCN+T3pd1tui8=,iv:AgemAPgRhvl0eW/xy6Qh6Qu+xoZK/QZUh6gpKgzIHI4=,tag:AI2Fcjux/5dOn32DHylPbw==,type:str]
    version: 3.13.1
