apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      containers:
        - name: jellyseerr
          image: lscr.io/linuxserver/jellyseerr:2.5.2
          env:
            - name: PUID
              value: "99"
            - name: PGID
              value: "100"
            - name: TZ
              value: "America/Denver"
          ports:
            - containerPort: 5055
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyseerr-config
