apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:jja5tjIR85jeeoDaHNfwpXAKW9ZONfstH7970ZrobZuaT6OQQ3OTfg3OnYsNhwTNle+3IwOzW3rC6PsoL/w5M5PnFXyz9JeimzQI7zfZzH5irhrRYtzakKAS6PSFrYE2Z3gNJz/+da6KQFgf81vFUhMeT5F+tj/fe0hdLJudizNHmh2CuOFSdKrpQtx6tZFBrAygaJr2GCXem5DEzvtHJ6msv3Dx+cC/2UnEGeyZLZENMXxyLScJ54E28rScsOOtPJD6B+pU1+Et0lEcYvq61phsvgAB7MDSRI6b3PgoitBvEUQhOQ5TjIkVEEE=,iv:c7PWuBsIPCm7Rd6//J6XoWao179JbNuFoGrsWO0a9Po=,tag:3au5HS3tYhLmC2yFKSYayg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaHNaU2lsdFYzci8xVjRk
            Tzc1VG1BUXM3T2Z0dFllenFueTMxT2h5L3hBCjlQNDd1bURHT2tWTHRqMUZNOWtQ
            czZuN2k2NXpleFl5VDhibWF6WlRiclkKLS0tIDM1Q1JqQnNwN0JIbmZSSFJ4SlpF
            WGRsSkI0TWdIUG9xYmxEaTRDYitxYzgKluk1MbhjSGyQpfxzbbAqLhObv/XPZ7HG
            iWvrLMvu1zjLbpwm4JKljI5VhPLK3p/P/5fD+N7uB9LdyRFqK84x4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T21:33:07Z"
    mac: ENC[AES256_GCM,data:wuG1Osf1ZwAZDifwxwcm8uFQ2D+jFgKVP1kzLyLB736cfqVm9V8XRdYCFpQg/Cy/2S2AsY8dieFPHKBnVvABmZTtChsEckmV/pGBZCwgeQA4042jzdJDDp1CDfxuBazgisCEVunnlVJdvXJaYwNXimN8iip1v663eZMpnFokA+E=,iv:AE2qFrZt91STwEJZjtwtdGVSbfTcG/QYkyrVo2kguyQ=,tag:/PLKAkEvvlS6DJLnjXI2GQ==,type:str]
    version: 3.13.1
