apiVersion: v1
kind: Secret
metadata:
    name: wordpress-db
type: Opaque
stringData:
    WORDPRESS_DB_HOST: ENC[AES256_GCM,data:4HiCEVCWdBhW3jtlOMAFwxHzMWrK1QibO0KdtM5yZUPE,iv:REiyRfpNXxdcDXnGnmazBqv9p7Cjssw8sVCnZ5TQa6k=,tag:lOhRYUP019LbMO+o3eYt9g==,type:str]
    WORDPRESS_DB_NAME: ENC[AES256_GCM,data:56VGaUOsy8moww==,iv:K33zfQJWwId+xRR7wzcSQk/ggqDNRXHyvBTat3Ldyrc=,tag:utr0GiB+wG5FrZEl1gLJyQ==,type:str]
    WORDPRESS_DB_USER: ENC[AES256_GCM,data:fGSJ2O4nRCUm8AvQ,iv:TL46b+OMj7ashGiLyegAoqYdGqhmZloOodj85V0OP7Y=,tag:7B+C11+fcnBW7MfQ/zbnjA==,type:str]
    WORDPRESS_DB_PASSWORD: ENC[AES256_GCM,data:lM6oDNG8Hc/5p4+F,iv:OfnKiMqf3yd9AYlCzPWBtR2QqGfYfqOzs5gaHcF5qRM=,tag:wmzS4/FkyzxNnkrDxSREyQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSzNKM3Zvb1RTMHpDN3hZ
            Q1FWNW1IQUFLM2l0NytITml0NkFCTnlxRzBVCnpReGIva2U1dTFpUHBweW5vRDBT
            dWtjdTBRZEhaRWE4eFIxMThyQ2xzUk0KLS0tIGpicDJiR0JVbVRjcmhXUDFBUU9U
            RkJuV0M1cU01K3V0SlM0b1VWVFMyRzgKXneAj7p9L9lFUUzwrZGFssIGyu+QDCld
            GJCXSEglYcP9altcZbrzrIPct7cNBgt2viogZp9FgsTfWPDomgex4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T21:39:25Z"
    mac: ENC[AES256_GCM,data:xoW/qru1f3Ngnm819k15QDIguYIXx25otwUzkE2RfM4w8J/668hIujwKoyxheP9cfJIQNEKayx+9LjNYvpUUnDPLPySAjCDNoGwZaubZ/WvbjnTFAW7kvstx3bH5Bo79H6x/MkyQpVfJ2FtPcitJdOODXa90LJ13KYNlwxSy6LA=,iv:MpXtWXiCv0evOXBu/6qfi33GPGqbAhZYVhLQn33u324=,tag:IpesniN1GSkFzCZ5x7pTgw==,type:str]
    version: 3.13.1
