apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale-sabnzbd
  namespace: media
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale-sabnzbd
  namespace: media
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale-sabnzbd
  namespace: media
subjects:
  - kind: ServiceAccount
    name: tailscale-sabnzbd
    namespace: media
roleRef:
  kind: Role
  name: tailscale-sabnzbd
  apiGroup: rbac.authorization.k8s.io
