apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-db-env
  namespace: forgejo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store          # <<< CHANGE ME to your secret store name
  data:
    - secretKey: FORGEJO__database__USER
      remoteRef:
        key: forgejo-db-username
    - secretKey: FORGEJO__database__PASSWD
      remoteRef:
        key: forgejo-db-password

