apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:5.26.2
          env:
            - name: PUID
              value: "99"
            - name: PGID
              value: "100"
            - name: TZ
              value: "America/Denver"
          ports:
            - containerPort: 7878
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: media
              mountPath: /media
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: downloads
          nfs:
            server: 10.10.10.10
            path: /mnt/user/Media/_DOWNLOADS
        - name: media
          nfs:
            server: 10.10.10.10
            path: /mnt/user/Media
