apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:6KzA5u9EsV7AKgPJk+yGC/aM3twahCWOHf7QJ4FObls1rNmMghiw66D/BNkrXHP4iKKT7ibAptFV8NARGpc5BMn6X3aWLWfsbXondrFJI6+bJOTpp/aSdbCTAwGizBhbKODJbWZY4p14QyQ8hDCbRfccp/DhkfAuBo6Y7uilfvnm5lfRuLejtbhXGiHx2gKF/5wjR/OxB0+Jl0GdeFjuSFrExE6X1YsiJXoiS72wowkQRnVfF4Teg6vhmiNI5Rj06BHyeMh6hkIJabpJk8gfVoUenft66nWrkG4n2y4JRIUIB/oqcp9L5CHAAQQ=,iv:MmpIm9+2enK+vByvdslFYIHs8udmBM2SFIo4JYfqdGo=,tag:HH/QHYnX57qVtdfMqE+d2A==,type:str]
kind: Secret
metadata:
    name: jellyfin-tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFV2RqSDZjaCtiWEFZV25u
            TkpBMDQ1eUxialVPc2NzS29LSDBtOFNNL2tRCnMrRDZoTlVLdStzTGNPSGIzTnZX
            R2NSeitxOW5FdVBUamZyTWRZUTZ5dVEKLS0tIDU5ZkhFeXM0elF5U3YyaWRkang3
            YXdVejVzWklSVjRQWWQrMER1emYwV2sKbpw+4JRWgtBcJ/xDiRn/tE0VMMSBrr+X
            BZQgqlrpokDa0jgLqZ6Qp3KNgUvErGp4FLNy1akvUNecobcSeg/rJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T19:40:41Z"
    mac: ENC[AES256_GCM,data:FWaRhmrkTw0qEGjPm2eihAIwEpZTfbeYdI5iL56TD3JqsOjqK3D/EVkrutWfQSfaa4IyoWW9KUxK/yTdJcdR7eVXbV8BYwK688aXyZ3qfcM31fU96wN7td00eeoFU7Lcwh9i3LCftQ+3SKkHonQV6JbH2zgNvk3vHZTo01qguCA=,iv:w9Cq6+As/seHI6PIFA+X4KsMbncjZUoLKhzvUAfSEbY=,tag:gTS3QI98zWMuAy2QbenYtg==,type:str]
    version: 3.13.3
