apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
  namespace: forgejo
spec:
  template:
    spec:
      containers:
        - name: forgejo
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              memory: 1Gi

