apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/forgejo

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: forgejo
      namespace: forgejo

