apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:elW7xEE++GgnGnwJQeMALgxPTnDUP6wCU7iJOncvI/HQSygbIu8zRE2nxG8ZMdohN6rHFnoGZVsYILYpRDjlvTzfqDA0pkHbXBkb8YiITRryX+QCL69s9FjieDL6dn+Tk1D6LI/CrZoI501ik9i3LJLDMUYtvGTZXXXplExSIGqPEgdVw/E/LDqK1eYCjSPCRdraLtofl6BHcD5Osxovi1n79he4+TNUlBkqlpsJqgfjqPbsaCPDB+poTp4w5/27MwZZ/1Or66rPF+vExVAuasCaZV8dSTNfYn7DAc9euBet3nBtZ7gs+YA8bAU=,iv:BKr93DLI43KtN6XWmfdxmkt5bU2Y9Fs5deXDVDSWAeU=,tag:DHwNB9cIpBbCHbjRHhT4pA==,type:str]
kind: Secret
metadata:
    name: radicale-tunnel-credentials
    namespace: radicale
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdWhHRzlRc2pwMElHNkl3
            YjZnM0kzaHZWQWcwMy9iVHBEUEdNOGRuWFFBCldCM3FBaWNrOWh3UVNNcTlzTFRH
            YjhNem02UVVnTnZGSUZUc00rVEVMSmcKLS0tIFhES1prTFVCWFMwSzlEdUlIVGhE
            OEdieUc0dE43WHZZMnVreWhwMml1bVUKNaNRHgWFItb+872LQVTPDgsy0PvXHGZF
            Da1a35jepqdBiDOpyrPN6ycRzzRUcEuoSq0xmxVAiL5u0qpSj0uFSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T14:55:33Z"
    mac: ENC[AES256_GCM,data:zU9IpgFoyRvANjvL2h5KKz7XAOf25fgJ8n54j09AZRvBNEd0/snixmFP7N44cSBU9voN3qgn5BZfNjzX5w5Hy8iVxU1D4G72pl+c4wQ3BtfIyMg7zsgeji6pT6V6B36KhDZ7ed0kVOKBZsDHTBTtNBtkAXA09CVND2ZYiAZH7JI=,iv:ET7doEpfeYfv+llHC0ECoWDmsThJ+zvkJXLuwOZhjPk=,tag:8lNnfsPtjqAfNMt2piAabA==,type:str]
    version: 3.13.1
