apiVersion: v1
kind: Secret
metadata:
    name: radicale-htpasswd
    namespace: radicale
stringData:
    users: ENC[AES256_GCM,data:7QZALOEoEZaSDoTGqGz6VOLX/Rp2Ch92OVeRz+iKOFJyGnSzp0FSbDOy6RJNZKkibcf8tsAj8590VbVX/ywUc1/6,iv:2bIyiZ0WpJze7qdK2YBQoVUPyOiU/Wra//6CVz84dTQ=,tag:ZI8NH4CayFxAEkk6F+9T/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eHFSUXd0S2hpTTdib2ZR
            UzdpNEI0ZVZSaVVyMHhLS3dXTlNkUGNBZFJVCmlJdkxxQjRNTnJwbUZrenE2MGc2
            NWMzQi9tYnlLa0EybHNwUlpRWFB4UEkKLS0tIHhHOVYwei9GeHRzNzYyRFc3ZFdv
            RFBkRndkeDVxQVl0UHZCYWNFVDlsMmMKtUQJkflZn8Za+PiNYDUvmZ6u86c1+tC4
            833Cncmr7uX7PqbZIhMEd+oOVUeiJKed1lJwNlR5SLI3/Dr9DWOMTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T15:28:01Z"
    mac: ENC[AES256_GCM,data:uZDpu9y2uqvJWy17LME9+SiqZAws/aMqfFPp2ePEPMocc9PwRsz08mz+5JkSpBWgaNXkXYz/8J3uRE6Bgz0HXlRGICA+XHc11A4PwFsjPj/tJ+cIkAl2zOPfEMjRGqFd8H3ppiLrzFV5ElFgeY9YgbwnabcPOhU5LMc5xEmMn/M=,iv:hz29dfbKzQ6GpzDc6ec0U+Lmw4j0Wqz+ZWG63FJY/+g=,tag:IX2LsWL/ZrCdvsOXQEWSwQ==,type:str]
    version: 3.13.1
