apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookshelf
  template:
    metadata:
      labels:
        app: bookshelf
    spec:
      securityContext:
        fsGroup: 1000 # www-data group ID
        runAsUser: 1000 # www-data user ID
        runAsGroup: 1000 # www-data group ID
      containers:
        - name: bookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.34.0
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
          - name: bookshelf-data-pvc-audiobooks
            mountPath: /audiobooks
          - name: bookshelf-data-pvc-podcasts
            mountPath: podcasts
          - name: bookshelf-data-pvc-config
            mountPath: /config
          - name: bookshelf-data-pvc-metadata
            mountPath: /metadata
      volumes:
        - name: bookshelf-data-pvc-audiobooks
          persistentVolumeClaim:
            claimName: bookshelf-data-pvc-audiobooks
        - name: bookshelf-data-pvc-podcasts
          persistentVolumeClaim:
            claimName: bookshelf-data-pvc-podcasts
        - name: bookshelf-data-pvc-config
          persistentVolumeClaim:
            claimName: bookshelf-data-pvc-config
        - name: bookshelf-data-pvc-metadata
          persistentVolumeClaim:
            claimName: bookshelf-data-pvc-metadata
