apiVersion: v1
kind: Service
metadata:
  name: navidrome
  namespace: navidrome
spec:
  selector:
    app.kubernetes.io/name: navidrome
  ports:
    - name: http
      port: 4533
      targetPort: http

