apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hugo-data-lh
  namespace: hugo
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
