apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hugo-data
  namespace: hugo
spec:
  accessModes: [ReadWriteMany]
  storageClassName: unraid-nfs
  resources:
    requests:
      storage: 5Gi
