apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:wgLnrVFAcmoFIc4P9/LbPvRu10VufpfkOpXtOdWRiSwqZcWMgbs9vow+GhgrkTd1K1SXAfMOoIu7xUy4yDRpEKwDSVEJGSaRoJksOd50EHVSa0/6kXLNTv6bSka5ZR8pdlHWx4Er9O4nNwiFRRje4Yxm13LcoCVVjW4LmgMya7uUv1uT8MdIRFpIYWxLnvukZZ3TINmnRf9P+sJa6fWYHmaUnBPHNhiXDs7zecNkk9fhbIlUtmdJRfFKOPcUHBFEHBlrXmnp4KJsbAQhTdWVVQHFRkuiId5BD9mibeptPgymiJPbt5Mk5A1jCmY=,iv:/JCyMQvp/L5gc5sMA1LSYc5E+7NufdmJ/in90S1nr9M=,tag:pLiI/MJC/yhhN8yq/9xiVw==,type:str]
kind: Secret
metadata:
    name: paperless-tunnel-credentials
    namespace: paperless
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUG5mS2E0dTgvbTgydFN6
            VjhJSVpGeDlydGh1bmtJTjVWcEdteCtld0djCjAzV3VhUngvRmd2Wko0WTBRSzg5
            Zjl6aVBWV0xGZG80V2JqUGFyZ1pEcWcKLS0tIFlZWjJiZkJOQzBmQkgxczMrbStr
            MjhIN0Z6c3BRb2RxY2VWUEZxOEFiS2MK9R1ycDW50q95ILJNbpy2ulBgJFLGkjIK
            yWE1Z9NyUJP0l/hxDLgK4owo1qBUT7GMidU892KPcbECcHjb9185hQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T15:27:39Z"
    mac: ENC[AES256_GCM,data:g83DW66bhXCGDERmpEt7HgMg13VcXzNndcCUh1xhk7hfWdo8OwH3OazqR4DMKouJl7XHLuVkDhQGrHtH+CqYMc4VrxCaimOvlLF58mYOo3OidAzgkbAGBUJMIgGpKEPcEo5lotOTF9pwVjW92s0xBcFT4eWKOXUQKrcnGtunAbU=,iv:eNAKA6VPxgAM/girvnioUf1+2UE4HXj79ufr8zddhRw=,tag:h7/UNjSyWJT6ecBl+TdGhw==,type:str]
    version: 3.13.1
