apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
    namespace: paperless
stringData:
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:dAdDwgLiFOvFPVQE,iv:gUq1rM9lhexPGJm1i5m8buuWuswYXQWjDh/ZfE8abQY=,tag:gBgtO+plTG8lVSsSvKx/qw==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:psk+mFMXhXqqERxp/CPPoTUny0GbWqmoWpveQm6SyMG/F+WteRjP2cfz8wqN223iKyBAVOXiiexz6EhDej1+ysiz9A1m8ocaCD9X8NEEFB7DmiILo1lO/U5RD9fCxDeKXKHXIg==,iv:0YitLn98aLltgl3jcobSIKuazYLsE7qjO6kSS31iMeM=,tag:+6kH7efmoYMzrZ1m5arNaA==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:4M//oCOi92Q0Wemy,iv:yF7/mH03VRbXuCz7W26VS+U38E+hODCibl8HNRtpyZI=,tag:DGeuruiusb83s1nfq+ELBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSclVFNUZaZ2RMdUdEcmRM
            alhDeVpoVUtFR0thNWdPN1hmOFRuOXJha3o4ClBVRmZHcUl1bThyV2pNUmZNeSto
            MThuWmJ4WmdnSWp1K0hOZ0RKMFVnQ3cKLS0tIE1BeENXamlvd0U5Mlo0SzIvTDQr
            aUh1VFBIeko5V1k2eHBHZHIrQ0VPcWMK5KUf0pxM1qdYGswV86yjw9j+Xk7mfsml
            4naU8J4yovrUDXA0l2DEBY8nC6m44F0ldeZQDTs7fUGEkXYiWvnPAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T15:13:43Z"
    mac: ENC[AES256_GCM,data:JQeIfx/ugYAXq74IDLnsQ7in85wH9eINBuKMYFagiK3HMTs5JOqzjnt2/q8wk8U/1wTulTCuKf3Q4Oaow3eBodm6J6eip3AM9zuZrsYS9vFYk5ZtDVNiNComoTfW/pJM6Rub8mK51hIjvQTuaIMXPwkdFaYrpUggO+7hqN8Gj2A=,iv:V1AOF+Ii1tF2qQ+3AXE1gwwoAMonyENhwzz1xh/ta6o=,tag:gWaWtISnvkmvw6yYpybIPA==,type:str]
    version: 3.13.1
