apiVersion: v1
kind: Secret
metadata:
    name: guacamole-tunnel-credentials
    namespace: guacamole
stringData:
    credentials.json: ENC[AES256_GCM,data:koLUtq/rxy/P5u+VG8W8278XetBel17dOHSzAzJorMCNpO2Q/bRgcu2yKcvwyYN3z+JmYa355rForltx3/i+zD20QZgNKyuAoP/QPn3xiS5EbJ4V6YGgQ5uGTzmupN4si6Wc2pLdtXmf+5MYyiqStNp9iLYt+Uq+a8gtMEDPfF1SlOfduNDNxHnzM6VHeClFKg7cWRAoqw3CJpJYgvJtQVaJBqmwwUmur+zr8FpaIs62IKVxB8XSZw7bNRy1M+SY6Qxvvons9ZBH4jXPfNo6QAtQqaR/3IJCYIa2at7wg6Cs1f4iGCnFeqhUFmLm,iv:PMf8174b8ZiNj59YdW/zcT79ohnbx5yqAEfRBsj/fBQ=,tag:l/yXg/V7IRc9XOAvJWbFrA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUWI3L0ErTzdlVFdRQ2Zo
            NnRHaVRaL3loWndlb0ZIZHVBd2lKVWNMNlVrClV6bVNhU2NLbVJsc04vdktxS0JR
            NVNXQmpmRnRuendLSklWaWNxWEJCR1EKLS0tIEIvd21KeHFVdVM4WjMwTS83TU5s
            TmJsZWZZWEErNGR6MTB6VmVxNWJ2YlkKWuuL9t4CoFLW8uumJpR7z0bL/gt4Aip5
            T+h9dBKHZNHW3C8UT1aWjiPLCOA9p67hQodOcsLUfuprfL4tCiOU+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T15:25:33Z"
    mac: ENC[AES256_GCM,data:8jvK8jjsNdOa9bAnW075Celh6tEJTh7167KwYApFVAM9p+HrYD41E3y3m5BY6Kz/6dXZ3yJ6m5vcCKLxWAi6o/ghZHqtOxpL/2biXwsscSfWSE8kJmH6qQVt02mFysonZp/ipNJ684RiuLyfpfCX3ECjKT/YK1IQjkJHHeB86KI=,iv:VBLf4RHdEbmJnjAs2drMBF56a2p+q0xiD9sc6DrOwbE=,tag:GxENqNC+aBWvXjbPs/8SWA==,type:str]
    version: 3.13.3
