apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:IgJSU0mkLmrWC9cu9oS348vQB7Lxsx15fXS9vX2EvsbrPi7zFKk8u5fI61wZXM9TSvMdlTKDJ/Hl6VZU/PyjyX5lKMmEUt14ujVbV+5qUXcwrNqQghNv2Gl4hdScUaZ+Lbw3r/2oJ5HmvrEw71yXaYNBnhLMiBNrCb5bykHW4Tq54ewhNPSTYs6T4rMFGikSWoKKiAhaExLx+rCUu2w0a91MZdoLNrcfrjyr0fzOtJ7RubJpUARJhIbMO4H1WFCbrHkelpLMBU0RqyvNrE0rnYGismF9RMcRHSi/KM34SSmO0dKuqXrPjn3Qd5k=,iv:xbZvCqjqcqr7bNILwrGwnyua0O7TER5w2ewnDhVPgSI=,tag:MR6Xh1pYtlitD3l7ZhKcEw==,type:str]
kind: Secret
metadata:
    name: guacamole-tunnel-credentials
    namespace: guacamole
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYVdrNVdLRm5hcGJPMnZE
            VUs5N1BQSWQvMzdlY3JjNUhzVE13SkxFWG44CmdkOC92cXFjb1lwTXcyMVJhem13
            Nmk0cEFGL3Z1VzZDbWZjS0orc3RxRlEKLS0tIGZ5NWxLQWk3QnFLWHBGSjZLZG85
            VXlBRCtNSno4cEUyTEs5c0hKMTVlVlUKKnOESp2eUXh1g8dXnmogm4hEb/npocIJ
            6fueNjnofkcEGCIPP8ULUfqbzE5hkqGZ8TPr/lMDddvSh8O0fdqzbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T15:42:07Z"
    mac: ENC[AES256_GCM,data:jZXGVbuq4onsrP45nJnVOfC+iZLoGh7515jh9HzAdVx/Y4p2XegZthsdgPL8fIpfdFvhArNy/3weD6fHaX3Nvd8rTff92WQIzqUsUgDEjAiBF8HzBfnl8hAH9Lq/Zz5r6EfSlGO0BR7Q2qpJ4DItfH8ARJzaC9szbKdGztOYUjU=,iv:gqWSBccrrX9bQtEwk0COZtFd9DKj1PiGbtwXZsWPmJ4=,tag:JUUHN4MzdfWWJva21LCeSA==,type:str]
    version: 3.13.3
