apiVersion: v1
kind: Secret
metadata:
    name: guacamole-secret
    namespace: guacamole
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:omm1VdwufG5wYtK4,iv:BrTdTzgDf6mb1QYSi550uhwjnetougnl/Xh2mY6/8bw=,tag:pZsvE8RObEbl5PpJmpBxvg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTlh2bWZxMWxsWWtrNzVu
            V21EbDh2azY5MHJRMVVxK2N0NFhzL05jcUJzCk5NeG9xUWNzZE1SQlpCSXlyS21Y
            SDVTclBCMDltODVSelFENkxWaXZ4TlUKLS0tIEdQQUwzRVZPZ0IwTWVPTC83Mlg2
            SmNTeW5HMVIvN3JPalpQcng2RlNjYUkKrpz5pm43lBRh8mGQ4zkTJllx9rW8TE69
            I2kW0dy/10Gj/PhXvX6k5SheTGUkU1YTd2HrWsfnIiSLxOcYhwjglA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T15:26:13Z"
    mac: ENC[AES256_GCM,data:9r+ObHo19cXXOLv80EqhgxxnvP4SRtqA77N1Agn1B/5K9bxmBCsdkJhPQw5aTNxIIwVBsmyn7R2hQsm2h6YW3PCWljky5NkXTfKVL6d/wgf1ZUbuiD+mw0gcfuYKlVb7JniqyE2Z8JPuSAzibRyzo/P0e+jkzX1RdEFQAmPNBDw=,iv:oYp9XUyPGzGMmRqqnXMB0bfn/VxlBoW6w5DLR4ZBE7g=,tag:PQ0Mj6i0b+hOV8dCAx5wKg==,type:str]
    version: 3.13.3
