apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:N0tRRe8JanDKDSeogqDH+ty+X2ZUSUmum9syPQveegXW7O2xP32uUNH28tN0bY3HNHVSKQeCOqxMEd+YRdBKW3cIJg9iMcvg+sH2Gv/Wu+B7WG/hbWxRdDj8n94skngv3UTGZjpn2aU7iRWmdOYa4URLzZMjiv0IHEChrkBd1DGZ22FToP/FSskIfZlBCcd99I9f6f/TSEv1pBDAroqSS4iEswOmb/I/16nkTQJzSyPegBNKehfLyLxBSg5b9SeKuUkxDYHWC1ZFjVeacjGo85ktPvceTGMR1VjArwx0pxJ28MLUowtaKLHUd/I=,iv:XEk0hFYNCtDXkzPPBfjq1A1J4151mISyHWoiAhADDjA=,tag:F9lxrT4DRQTI+jAkJmHMOw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVTJHQkkxZUxrdW1WRlUv
            WjdVUzNXcTVlOXBFVjJYeFdPN2F6TEpyMGtjCnVPaVRDNmZrZ08wVk43ZFdrWk9B
            VDhHd1lSWU9STk8rU0t5Y093ZmR6dnMKLS0tIEMvaC9Nd3RlSVRoSjYzbWZ3SlpX
            RDRzdHZRbGRDZUtlUXQxNGY3OC85ZG8KRQlYU3CNDLEJrOaqGbNnoX5azTwUvZqx
            d5PUvdwrLsDatHB+rOQeGdEseinuObc4gH9zy/cxzflry85b4+D7fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T19:06:54Z"
    mac: ENC[AES256_GCM,data:mnnd5kvWPwJHPIHUAuxESW+lDjpsz8aFCRcXeTxCJLPGlmqZckqR8DPdM9QCFVMkpBxL0OWrcgNTmttfw8jAMq8mNCdKsg2g4IafR6PBxM0fPVpbMIolGC0560DAXp+FZmjq1x/T/olztBI7XhgDoFVyndz25Vrv8Xxkxw7TZDI=,iv:/vjC2zD+vbkIF2PoGJcKCaDpoALN5Av84DoTIi2lPFE=,tag:jhm4mHh+O57UfAqe6BuZXg==,type:str]
    version: 3.13.1
