apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:/mANGqhYwGDySK87fsdmtJ9Px52co0Qp4gquxkma+ZihW36Di9FQhR6M9U/annzCZkDhjLi1gjT4jQ0129avV64F+9zRED8VlZfA5f6kILrF6uKWzFXmK3kkXTwVSNzZSQzzs7HrCeV7ucJoHg0PbETy7xp+HlMkHYI8bplHIR8VeHwJ5oDaIgPzCPm5Nin0IHF5V0Mzpp8grgVdNE8ruJSR7rH8cPjdO2/r8X1cHvjLDb4Z0mdA9Tn3ngruoNlhy9tgehZFLN1GWax7i7RvmzdduUrefQHB1SjfM0WGN1aQKYvFBm0tinW950s=,iv:M6yKqkJQuLo2A1B0d6KuquwZa5VHslUwKKH237/ihAM=,tag:BH1oaRiUI5lcbx/gjHcLuQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UklkRkRtbXJzNVZWMVYy
            SzZPakdIRk5JTGx5RXFSakkwMXRsbUhUaG5FCnVESUdORTZtMEx0ZWptdGo4NXJa
            MkNPMlRFUXREb2Q0RDl2K0VZaUVBblEKLS0tIDRRM21XVXVBektFS2MrK0FtelpC
            MzliUnFkM2RRYXRKRjdGbHljQWFOOEkKi6BdvYFCTijxN/nf2SRuWa9YATFXswXI
            KE1iKaoLod4V0kZcbBZqaezjZ6wRuf1Un7fwWfzeKArb0LvGkj/EcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T19:53:19Z"
    mac: ENC[AES256_GCM,data:6qPEBqHZDNbj7KfJDPohjCdg+O52EewP14IgaIJqgwLm6BZhr985OJlCjxq0kzcT8Ape/ugNd0lpEgt+TMQhve8qKGUufh4kzlSyV7k1PTvAiz16QTteqxyQsjFhR+tQIn+AhYVlWrjd/m1I4kbeNhspgs20xTpjBUxzkfc2S9M=,iv:WoqPnCqIxPUPVIPYegyybkKgS4i3kjUob7OUxP86BB0=,tag:CQQjbdkl79z9JVtsle+U1A==,type:str]
    version: 3.13.1
