apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:7s5GaSci3fQfiGMw//z92ILzsOWNGTOTKY3mKKeF9mUKqT0t/JG7dUlnszDmDkVtBydaLlAY+aGo39IPOnx6y6yXFspCAvf29S55vzSUq1BXUIfFY9IRSsvpWgh1xqlVWJPoSWe1yrEF68SuRdy3bS+bY6DNUqsDe2gsC1+U8oFuh4tl8g2Jz9M+H7UJb6Osx9Qx2wr/ozPFdDLM/V/cnJ3zw1lGFTo7zYRox3NqW0o7kbqkXIZJR4M2bEKmOeZevllyVJlEUeG43QdAR1ym+oOC2XrVflCiUIR1zzDgLOEMmf46tBg5C58cv4s=,iv:QHVylX3tFnmIeuBFqZ8lZwGZ8RuwZGnd2eH62Xc1HSw=,tag:H5pUHArPWVaexDGvsL0g0Q==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZWhUWFJkajBFUEhBMXBJ
            Ukd2ZlhyMnJOUVBmMGNDOStrUnFEd3llRUJ3CnJwREZQWUVob0tQY2tiUm9lVFlm
            VzlYKzJkdTVhb0JSWHBOa1lIRVRjdG8KLS0tIE9jVWpFYk1vWWx1V010dlRXQmNt
            SHlFWU1JR0d0NTVBUjljTjhnd280cG8KObj3cmqiLADQrwsSFE+W1ODh8FpDydDM
            UBFMyHwfek5NsdB52m7hiLAM9OcyLgzr+22a8QwE1C3kzkRpE6Ncmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T18:29:02Z"
    mac: ENC[AES256_GCM,data:+T+twFmGdyNVurlxHaRVEEXxyCqkpA4YzFY/wl4QGddHJn2E52ddelQnGMV7N8hIMmRbEbk/60Qs/Vgyn33VgM2jAFUasizPU5hZJwUzNzBHdGuITu+fbuVfjsA8yBKRuFoLZDI6HqOkroGoCGJYu74rVDfqUy+laa9HgxrrfZM=,iv:i0H3ga/gLRA0eCs1FaIiXenX+2cIBWOMwxLOarAapas=,tag:wck7vr5uGtL+dD/NC+LOdg==,type:str]
    version: 3.13.1
