apiVersion: v1
kind: Secret
metadata:
    name: wordpress-db
type: Opaque
stringData:
    WORDPRESS_DB_HOST: ENC[AES256_GCM,data:V2pfJzHob8Ac8x960WEfCDkHztaV2HbP8Yz53QMVDquU,iv:UNiQ4vhVS/Z8Dc0BIr3zkDOYbLQ1j9R9f4ufCc8dcMk=,tag:6/oOGvaosnaMTdA5Op0tQA==,type:str]
    WORDPRESS_DB_NAME: ENC[AES256_GCM,data:3+vNAls0OMU6NJ8=,iv:mI6jxe0/+zRXqD5Epzhjgsj93FZgDRt5/NtJbRqhJX8=,tag:xS12zCv8Wzr0ZkEkLzJ0mQ==,type:str]
    WORDPRESS_DB_USER: ENC[AES256_GCM,data:NhwlANzvtUSD+RV5pw==,iv:kTm1UIg01JkH1iaKzkx/2ULCUtZbYkL4ktPU04bpGJw=,tag:IFAEiQwkVj+T7sEi2TSNpg==,type:str]
    WORDPRESS_DB_PASSWORD: ENC[AES256_GCM,data:NmB0OiBMPVCsO39o,iv:CklpLflCbLNecNoHocE+mPJCIDsisgYM2dTOHNer8mQ=,tag:9bhSpfAiBfwkNHc0Tp3O0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnYzErSEt2Ynp1bTlVMWUv
            bGE2bTdTQ1lKdjhuUEwrV0lOUVFjRm5LVndrCmpqeWRObmZaTkVoTUo3cklNVFQ5
            U0MxV25VVWdYQm1SY1gweHlscjRpT2sKLS0tIHJaS3daTDlMclVIVEN1K0tKSk5T
            Y0hFQlZOTTIvWWVJbldWQ0ZiamFMZnMKe8uW2G8jLxmoFAGnhTg1FXjFZqC7RKoV
            b/kuAP49tnhNY9wEMISEErpAeYZHQZzr2OxxTrcI2OYX88lkbUvjrA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T19:09:29Z"
    mac: ENC[AES256_GCM,data:Ejbyn5J6DJW6sW2EZ2nBC5o1mQrFZCIku8woXJnqIaEelGvnafEXk7Q0koGP2h6H2Fa86t1s3MRKifhfU0uEEJYah9LFMPnQC5Ky0d+dCS9BvptbYDqDkKZas+QqV40QUj7Pw+x4KoSxWl4UnLO/VvSgHCGo4KqYZ9jbtynCFJc=,iv:ogkXfPzkF0yLMt4j0dN5EJm7IV5GAkGq1AVXWi04ekk=,tag:SRSXkptvIIssY7PSTPZM1w==,type:str]
    version: 3.13.1
