apiVersion: v1
kind: Secret
metadata:
    name: wordpress-db
    namespace: wordpress-zoomzoom
stringData:
    WORDPRESS_DB_HOST: ENC[AES256_GCM,data:yBAennhGzdWWy3wEp/enrHyhuGwqoRRG9mwM24I2DZpY,iv:MhPZ/qlIdFJVJZ6jUhuyMtl0x6PwE+E2Bb//UlgigqA=,tag:JGY/BGY09nzLsTdpML/2QA==,type:str]
    WORDPRESS_DB_NAME: ENC[AES256_GCM,data:Qy9kAcJrYilgtro=,iv:wglXte829RFJdCdgW33KFaHxNWYUggC1pYbg280ljc0=,tag:tnwaNy8X+QlaYcogUHfu2g==,type:str]
    WORDPRESS_DB_USER: ENC[AES256_GCM,data:dnRmdWCWltFN8Aj3LA==,iv:hMbQzo5dBMFjJDxipX3slFMppQp6H26Nm+MQs15oVlM=,tag:1JHvtJVpnK8zflhbw/yCCg==,type:str]
    WORDPRESS_DB_PASSWORD: ENC[AES256_GCM,data:x9TYiQvm6WI4tPHN,iv:WHjmXFSkANf4AN2IVPWxdy6uxilAuGpOCblJQ7Sb1j8=,tag:olJchvuK4KE2aSHHwMuvQA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHOVVCa1laTXBjUGJBMUJ6
            RTRkZDI0eVNDSDFSbUEyUy81VWJ1Wk1ZTjJjCjZ2MmNldGM1cld1S3pWY2FNZGFa
            TjRIakFCelBpamZnRnJEOUtkY0FZL2cKLS0tIHFTRWNyVUtxU3VycjllV2pZZXVz
            bVRHeVRxeUc0cjJwRDJJdGVmTGxQZ00Kh+wd6rEOM8Whp6t1Eq9srwkg7a52GNM9
            vihfp4eSudvHO7BZcsCA8vU29swqK7EomHPlScTp77HkixN5CTTecA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T19:22:39Z"
    mac: ENC[AES256_GCM,data:Up+VuAxQTuK4LcTlQptZ39PlnC8lc4wKyJF2jAQYKx1WGagevd6xGA57jbjXJUXslwHCAT7PI2MYvZUSzCzcZ/nswirStdcKETa6HIiBlZLYrlyFS5Kj4YPI0KKmqr26w57MKkbmwj5U5G+bpLZ29b8JMzgd/xnFmaLD/cy2fQ4=,iv:Q+WOGZ8aZa3+4MF+7Vm50VHwQcPKWT8vSEFiP0kX9UI=,tag:3Lx/sCDScL9EAiXsRlLgOw==,type:str]
    version: 3.13.1
