apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress-zoomzoom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      securityContext:
        fsGroup: 33
      containers:
        - name: wordpress
          image: wordpress:6.5-php8.2-apache
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: wordpress-db
          env:
            - name: WORDPRESS_CONFIG_EXTRA
              value: "define('FS_METHOD', 'direct');"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: wp-content
              mountPath: /var/www/html/wp-content
      volumes:
        - name: wp-content
          persistentVolumeClaim:
            claimName: wordpress-content
