apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-content
  namespace: wordpress-zoomzoom
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: unraid-nfs
  resources:
    requests:
      storage: 5Gi
