apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-content
spec:
  accessModes: [ReadWriteMany]
  storageClassName: unraid-nfs
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-content-lh
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
