apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
  namespace: mariadb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: unraid-nfs
  resources:
    requests:
      storage: 10Gi
