apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
spec:
  storageClassName: unraid-nfs
  volumeName: pvc-b5819813-fd2f-455c-a79b-4d4fe215af52
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
