apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:ML3bhKLSU1h6vcD/MWRTCmrghlZrRlXS45tjZhVUkHG+z9Xwstag/jbDc2CLPJ1CoAVOT1EbVQI=,iv:NNJi+gGLOW6r4DW1xjXE1X7NCOxHllirX4QhH4IJCxc=,tag:FSib5MwG5IyTxnS4RKF+hg==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRTcvbVdrMFpPZ05rUXNl
            ZlptUVd5WC9wMDAzUmt6MXp2c3poOWRsY2xnCkpyaHhXUUhUVGczY01waU5Ha2Q3
            dFhJUXdtQ0VWTGdaVGcvRzdMdVdzTzQKLS0tIFFiWjVnM3dOaEFTaXYzS0k0ZEY2
            RDJFRnFFS1kxQWRrWVJNOGgrU0lTakUKVRqaQO7GCa9Fq2nEjOUFmvlEXm1U7KaI
            hk3eyAS7CWcmikiB9cwl/DQGX2TRAWT5pFB57M9L3Ozm1TYSf+CDZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T17:53:55Z"
    mac: ENC[AES256_GCM,data:uedu56dgdVJDoDCMFbOmzg7o4hIMzUYR/cZUzoWAkt6kZApglGy3z2FRouXQqULuyLWxP2BRYxo3GUUOA2c6sR4/pgyzCzfU6qI7mphFlLpUp0LUWGCdKd9ye1VUxT/+yO+DE3RV6cdzsfr/30o8L4/T5xB/3q8Fpe6wA12yE5I=,iv:sjP9dZaNIicyDTG4ok8NzybLIYwxUNBLyvybK72krOo=,tag:1EWgToI4X+SNN/f9Zoe6pA==,type:str]
    version: 3.13.1
