apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:Qm8kGKBJkZbAqmR/aeZtFPZnUs+UOv1xpHqTxIZyUDPFeNeE/utcfC28vdYblrqYMk9JqPASDAE=,iv:f/ExM9eU4Twpz7iFZJ4PFmpAs4xdWHKTaXS/Z7Bd5PQ=,tag:z5ncr3N5VFUWDk5P9cW7wg==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQU5QYXlSdzMzOTFVeXRj
            OUkyOGNabW5mUmh4SjlmVzMrUENFa0E3V0JzClVteUlNOHViSzZDb0R1eXl5TGNa
            WTVBZUNrcHhyRlc0TzJ2K1IrK0VIZVkKLS0tIGMvUEpwelc0Mk5YVVJQd09EZmxw
            SlpLUHlvRDN0R3ZNc2QycTVDdUt0K0UKGRHIYTDcNwKXyiXheFMkzhnMj3N4h+oC
            0u0v7GNyALtWxYlZ5QRPMjM+3m9W8HrxWtGHRP2ltdr25V2thFYcBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mah2f0v3cjpu6v7d4ej0qjswqfggh9lru0yeywh49fyyd5wlwqyqykafvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T17:18:22Z"
    mac: ENC[AES256_GCM,data:c1BhgMogmoTmnodZA7BxfIvEQKH2S3qYNoNghSyOe+1iOxA4LukXu8vF+J8I83Tp63LXSnyj5C+9quD2ciyXHS8L9c0TCz+l66XvHngyaczqt9sMthWWvNrPNLbRB8H4WJ3bMtUiVkUYMzKneiLJ7+jZu45H+/U6jVNdIDKIniw=,iv:7tfGxQO8z57Xi4qNd2NKb7aXCr47HQqUtwB2bu71VDY=,tag:+w0p4Q1RFx2q2SMprr/ukg==,type:str]
    version: 3.13.1
